### ISSUE TITLE
All links to Angular2+ demo are broken, where to find it?

### ISSUE THREAD

**Issue by FirstImpression** [coreui/coreui-angular#1]
Is there any Angular2 online demo available? The links on https://coreui.io are broken, eg. :
https://coreui.io/demo/Angular2_Demo

Is there a PRO version for Angular2+? 

Thanks

**Comment by jefersonalmeida** [comment]
https://coreui.io/demo/Angular_Demo

**Comment by xidedix** [comment]
https://coreui.io/angular/demo
