### ISSUE TITLE
Default layout and sidebar functions in apps with right to left direction

### ISSUE THREAD

**Issue by EinatGit** [coreui/coreui-angular#101]
Hello,

I'm using coreui-angular template.
My app is a multi-languages app. some languages require the screen elements to appear from  right side to the left side.
I've managed to to that by changing the dir element to rtl by language.
**This is the result:**
![rtl](https://user-images.githubusercontent.com/40701229/74826403-3614b700-5314-11ea-900d-50d03f3c9ac2.png)
while the ltr looks like this:
![ltr](https://user-images.githubusercontent.com/40701229/74826447-4c227780-5314-11ea-8e59-c853996a12bd.png)

The problem is that the layout doesn't fit to right to left features and all the sidebar functions (like toggleOpen and more) doesn't work.
Is there any feature that handle right screen sidebar and other elements  in the default layout?

**Comment by xidedix** [comment]
Hi @EinatGit 

this is an example of  https://coreui.io/angular/demo/#/dashboard with `<html dir="rtl>` 

![image](https://user-images.githubusercontent.com/20643598/74830480-87707680-5313-11ea-8591-256f69aadc8b.png)

- sidebar functions work as expected
- you can try this directly in dev tools of your browser
- or modify template source adding `dir="rtl"` to `html` tag in `src/index.html`

**Comment by EinatGit** [comment]
That's work.
Thank you!
