### ISSUE TITLE
Add AppSidebarNavComponent/AppSidebarMinimizer to public api

### ISSUE THREAD

**Issue by coyoteecd** [coreui/coreui-angular#110]
These are components I directly embed in my app's layout.

Reason: for unit testing, I need to import them in my spec file (to e.g. inspect navItems input parameter and verify that it was passed with the correct items). Trying to import @coreui\angular\lib\sidebar\app-sidebar-nav.component does not work due to webpack (I think). For now I hacked around by importing the generated alias:
```
import { ɵq } from '@coreui/angular';
```

I am willing to submit a pull request - it's just a simple change - if you are okay with the suggestion and willing to publish it.

**Comment by xidedix** [comment]
@coyoteecd you are welcome!
