### ISSUE TITLE
Support of CoreUI v3 and Angular 10

### ISSUE THREAD

**Issue by coyoteecd** [coreui/coreui-angular#111]
Are there any plans to support latest coreui v3 versions and Angular 10? I'm using coreui-angular and this blocks me from upgrading to coreui v3.

**Comment by xidedix** [comment]
We are working on it.

**Comment by regstar** [comment]
Nice to hear. Is there any release period of time? 

Is a Repro to have a look at the upcoming version existing? I found the only v2 at the moment.

Please write a comment with some more information for us. Big thanks!

**Comment by xidedix** [comment]
Please take a look at v3 alpha preview https://coreui.io/angular/demo/v3.0.0-alpha/

**Comment by gperdomor** [comment]
@xidedix any alpha for the free admin template

**Comment by saps31** [comment]
I am currently using 2.9.4, when are we going to get version 3 for angular @xidedix ?

**Comment by himanshugajjar** [comment]
> Please take a look at v3 alpha preview https://coreui.io/angular/demo/v3.0.0-alpha/

It is making use of ngx bootstrap control (https://valor-software.com/ngx-bootstrap/#/documentation#getting-started). Is this going to change in final version or in near future releases?

**Comment by xidedix** [comment]
@himanshugajjar We're dropping most of the ngx-bootstrap components, but you can still use them if you prefer.

**Comment by bolivir** [comment]
any updates about v3?

**Comment by Codem3ay** [comment]
+1 Would love to hear news about a possible release date for CoreUI Angular V3? Is there any repo holding the source code to look at the source code?

**Comment by Codem3ay** [comment]
any updates about v3?

**Comment by ziyaddin** [comment]
Any updates on v3?

**Comment by Codem3ay** [comment]
Any updates about v3 please?

**Comment by Codem3ay** [comment]
+1

**Comment by coyoteecd** [comment]
@xidedix now that CoreUI v4 is released, is there any update on Angular support based on v4, or should we treat coreui-angular as abandoned and fork it?

**Comment by xidedix** [comment]
@coyoteecd We're going to keep `v2` alive and merge some updates. `v4` is in the works - fingers crossed.

**Comment by regstar** [comment]
@xidedix Good news, but I hope it will not takes so long time.

**Comment by mrholek** [comment]
@regstar this month we're going to release alpha/beta version, next month stable release.

**Comment by regstar** [comment]
> @regstar this month we're going to release alpha/beta version, next month stable release.

This sounds very great. Good work. Thanks for sharing the information :)

**Comment by Codem3ay** [comment]
> @regstar this month we're going to release alpha/beta version, next month stable release.

That's wonderfull. Thank you

**Comment by Codem3ay** [comment]
@mrholek Any news about v3? Thank you

**Comment by Codem3ay** [comment]
> @regstar this month we're going to release alpha/beta version, next month stable release.

Hello @mrholek ! Hope you're doing well and again great work on the coreUI admin template. Any link where we can test or check the alpha/beta version?
