### ISSUE TITLE
Open Sidenav Menu in code

### ISSUE THREAD

**Issue by XxQuickSilverZz** [coreui/coreui-angular#121]
How i can open the sidenav in the code? 
Because i have removed the header and the Buttons are moved too. I want to open my Sidenav by a own button in a Different location. 

I use Angular 12 and the newest CORE ui Version

**Comment by XxQuickSilverZz** [comment]
why closed...

**Comment by xidedix** [comment]
@XxQuickSilverZz with coreui v4 you can use
- use `cSidebarToggle` directive for your custom button, see: https://coreui.io/angular/docs/4.0/components/sidebar#c-sidebar-toggler
- use `visible` property of `c-sidebar` component, and toggle sidebar in code, see: https://coreui.io/angular/docs/4.0/components/sidebar#c-sidebar
