### ISSUE TITLE
Navigate to route on AppSideBarNav parent menu click [in Angular]

### ISSUE THREAD

**Issue by NatashaEm** [coreui/coreui-angular#123]
Hello! This issue is identical to https://github.com/coreui/coreui-react/issues/98 but in Angular. When the user clicks on a parent menu item, it doesn’t navigate to the path specified in _nav.ts, it just toggles the dropdown. Is there a way, in Angular, to override the default behavior to allow simultaneous toggle and navigation when the user clicks? Thank you!!

**Comment by xidedix** [comment]
Hi, 

You can use `EventManager` at DefaultLayoutComponent level, and listen to user click on sidebar parent menu (aka nav-dropdown-toggle). Should work as a workaround at least.
