### ISSUE TITLE
Angular 13 support please

### ISSUE THREAD

**Issue by nfoenki** [coreui/coreui-angular#124]
Some errors when upgrading to Angular 13 :

- Package "@coreui/angular" has an incompatible peer dependency to "@angular/common" (requires "^11.0.0" (extended), would install "13.0.0").
- Package "@coreui/angular" has an incompatible peer dependency to "@angular/core" (requires "^11.0.0" (extended), would install "13.0.0").
- Package "@coreui/angular" has an incompatible peer dependency to "@angular/router" (requires "^11.0.0" (extended), would install "13.0.0").

Do you plan to support Angular 13 ?

**Comment by Codem3ay** [comment]
up

**Comment by justweiwei** [comment]
Up, thx

**Comment by meriturva** [comment]
I guess you have to move to version: https://www.npmjs.com/package/@coreui/angular/v/4.0.0-alpha.3

**Comment by xidedix** [comment]
Updated to Angular 13
- CoreUI 2: v2.13.0
- CoreUI 4: v4.0.0-alpha.15
