### ISSUE TITLE
Angular Fontawesome integration

### ISSUE THREAD

**Issue by nidhinkumar06** [coreui/coreui-angular#125]
Is it possible to use the Angular Fontawesome for the sidebar  nav items in CoreUI

[Angular Fontawesome](https://github.com/FortAwesome/angular-fontawesome)

Right now we are using it in the following way

```
export const navItems: INavData[] = [
  {
    name: 'Parks',
    url: '/parks',
    icon: 'fa fa-map-marker',
  },
  {
    name: 'Organizations',
    url: '/organizations',
    icon: 'fa fa-building',
  },
];
```

But in the documentation of Angular Fontawesome, they are using the icons in the following way

```
<fa-icon [icon]="faCoffee"></fa-icon>
```

Will there be any support for the Angular Fontawesome in the upcoming releases or is there any hack that we can use it?

**Comment by xidedix** [comment]
​At the moment the way is to use fa css classes as `icon` prop like in your example.
​We're working on universal solution to include angular-fontawesome component (or any other icon component).
