### ISSUE TITLE
Sidebar not hiding when a menu link is clicked on mobile view

### ISSUE THREAD

**Issue by bot101** [coreui/coreui-angular#13]
The sidebar does not auto-hide on mobile view when any of the menu links are clicked, and the user has to click the hamburger to hide the menu. That doesn't make for good user experience. Also, the current structure of the template doesn't make modifications to the sidebar (apart from styling) easier because of how its currently bundled as a node dependency. Making it a standalone component or module that can be easily modified to correct issues like this one would be a great idea. Thank you for a great template!!

**Comment by xidedix** [comment]
`v2.0.0-rc.1` fixes: Sidebar not hiding when a menu link is clicked on mobile view

**Comment by bot101** [comment]
Thanks for the feedback
