### ISSUE TITLE
Declare @coreui/angular-icons as peer dependency

### ISSUE THREAD

**Issue by coyoteecd** [coreui/coreui-angular#130]
I have tried upgrading from coreui-angular v2 to latest alpha version. One of the things I've ran into is a weird error:
```
Error: Cannot resolve type entity i19.IconModule to symbol
    at [redacted]\node_modules\@ngtools\webpack\src\ivy\loader.js:78:18
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at processImmediate (internal/timers.js:437:9)
```

Turns out this was caused by me importing SidebarModule in our project, which in turns imports IconModule from `@coreui/angular-icons`. I think this package should be included as peer dependency, because the error is not really straightforward.

**Comment by chrismclarke** [comment]
I had the same issue, also when adding latest`@coreui/angular-icons: "^2.0.0-alpha.1"` I had the following issue

> ./node_modules/@coreui/angular/fesm2015/coreui-angular.mjs:13264:208-224 - Error: export 'IconDirective' (imported as 'i5') was not found in '@coreui/icons-angular' (possible exports: IconComponent, IconModule, IconSetModule, IconSetService) 

But looking at the repo I could see newer release which fixed when pinning to `@coreui/icons-angular": "^3.0.0-alpha.4"`
