### ISSUE TITLE
Issue with importing LayoutModule

### ISSUE THREAD

**Issue by miniminivan** [coreui/coreui-angular#133]
Hello!
I am facing an issue with my build and came across this error:
`error NG8002: Can't bind to 'appHtmlAttr' since it isn't a known property of 'a'.
10     [appHtmlAttr]="item.attributes">`

So I imported the LayoutModule in my app.module.ts file and now I am facing this error:
` Error: Module not found: Error: Can't resolve '@coreui/angular/lib/shared'`

which fails to compile. 
Any help is appreciated!

I am using "@coreui/angular": "^2.9.4"

**Comment by xidedix** [comment]
@miniminivan - coreui v2.9.4 for Angular 9 still works albeit it is deprecated - we cannot reproduce your issue

`appHtmlAttr` directive is used internally by AppSidebarModule and AppHeaderModule 
(there no public export of LayoutModule)

also:
- what is your Angular version? (see: @angular/core in package.json)
- what is your **actual** version of `@coreui/angular`? (see: ./node_modules/@coreui/angular/package.json)

**Comment by miniminivan** [comment]
@xidedix 
interesting, I have both of those modules imported in my app.module.ts. This issue with the build only came up last week, and the code that is triggering the error has not changed, so I am not sure what has happened. 

my Angular version is: "@angular/core": "^12.2.10"
and the actual version of @coreui/angular is: "2.11.2"

**Comment by xidedix** [comment]
@miniminivan that's weird. 

Quick build and run test here for Angular 12, node 16.x, npm 8.x, typescript 4.3.5 and @coreui/angular 
- 2.11.2
- 2.11.3
- 2.12.0
- 2.13.0
all works as expected. 

Any changes in `navItems` btw?
What about removing `node_modules` directory and `package-lock.json` file, then `npm install` from scratch?
Also: we recommend use v2.12 or v2.13 for Angular 12 and 13 (Ivy).

**Comment by xidedix** [comment]
Omitting the brackets renders the string `item.attributes`, not the value of `item.attributes`.
see: https://angular.io/guide/property-binding

_The brackets, [], cause Angular to evaluate the right-hand side of the assignment as a dynamic expression. Without the brackets, Angular treats the right-hand side as a string literal and sets the property to that static value._

**Comment by miniminivan** [comment]
Was able to build after going back to 2.9.4, will close issue
thank you for all your help!
