### ISSUE TITLE
"light" is not a known CSS property after update to Angular 13

### ISSUE THREAD

**Issue by Bykiev** [coreui/coreui-angular#134]
Hi, just updated to angular 13 and getting this message on build:

```
[WARNING] "light" is not a known CSS property
style.css

light: #f0f3f5
right
Did you mean "right" instead
```

I've upgraded from angular 11 and @coreui/angular 2.11.3. I'm using coreui free admin template.

coreui installed packages:

```
"@coreui/angular": "^2.13.0",
"@coreui/coreui": "^2.1.16",
"@coreui/icons": "^2.1.0",
"@coreui/icons-angular": "^1.0.0-alpha.4",
```

Thank you for your hard work!

**Comment by xidedix** [comment]
nothing to worry about - it's a build time warning only
it comes from @coreui/coreui@2.1.x css styles library 
(kind of workaround for lack of support for css custom properties in internet explorer)

**Comment by Bykiev** [comment]
> nothing to worry about - it's a build time warning only it comes from @coreui/coreui@2.1.x css styles library (kind of workaround for lack of support for css custom properties in internet explorer)

Thanks, but IE support was dropped in Angular 13, maybe you can remove these properties for IE?
