### ISSUE TITLE
remove right side menu toggle buttons (hamburger button)

### ISSUE THREAD

**Issue by ngingihy** [coreui/coreui-angular#135]
In the app-header, how to remove the right side menu toggle buttons (hamburger button). There are answers on how to remove both hamburger buttons but not the only one on the right

**Comment by xidedix** [comment]
@ngingihy for coreui v2
What about https://github.com/coreui/coreui-angular/issues/4 

```
[asideMenuToggler]="false" 
[mobileAsideMenuToggler]="false" 
```
