### ISSUE TITLE
Angular v14

### ISSUE THREAD

**Issue by gaweCodes** [coreui/coreui-angular#137]
I want to update my Angular application to Angular V14. However, @core-ui/angular's peer-dependency still requires Angular v13. When can I expect the corresponding update?

**Comment by xidedix** [comment]
@gaweCodes testing at the moment - we're going to bump angular version later this week

**Comment by gaweCodes** [comment]
The latest update allowed me to update to Angular v14. If I serve thy app i get the following messages:

```
./node_modules/@coreui/angular/fesm2020/coreui-angular.mjs:5:0-84 - Error: Module not found: Error: Can't resolve '@angular/cdk/coercion' in 'path_to_node_modules\@coreui\angular\fesm2020'

./node_modules/@coreui/angular/fesm2020/coreui-angular.mjs:13:0-44 - Error: Module not found: Error: Can't resolve '@angular/cdk/layout' in 'path_to_node_modules\@coreui\angular\fesm2020'

./node_modules/@coreui/angular/fesm2020/coreui-angular.mjs:14:0-42 - Error: Module not found: Error: Can't resolve '@angular/cdk/a11y' in 'path_to_node_modules\@coreui\angular\fesm2020'
```

@xidedix  Any ideas how to fix it?

**Comment by xidedix** [comment]
@gaweCodes 
do you have @angular/cdk v14 installed as a dependency of your app? see: package.json

**Comment by gaweCodes** [comment]
Problem solved. You can close the issue.

**Comment by coyoteecd** [comment]
@xidedix could you still publish a patch release (of v2 and v4) that has peer deps updated to include Angular v14?
I am getting an error when npm checks peer dep compatibility:

```
14:50:25  npm ERR! code ERESOLVE
14:50:25  npm ERR! ERESOLVE could not resolve
14:50:25  npm ERR! 
14:50:25  npm ERR! While resolving: @coreui/angular@2.13.1
14:50:25  npm ERR! Found: @angular/common@14.0.4
....
```
