### ISSUE TITLE
[Help] Migration guide from v2 to v4

### ISSUE THREAD

**Issue by a-h-abid** [coreui/coreui-angular#139]
Hi there,

My team is planning to upgrade Core-UI Angular from v2 to v4. Unfortunately I'm unable to find migration guide for v2 to v3. I did found migration guide for v3 to v4.

Could you please guide me on upgrading from v2 to v3 then finally to v4 ??

**Comment by noeljoaquin30** [comment]
up

**Comment by Iotonix** [comment]
> Hi there,
> 
> My team is planning to upgrade Core-UI Angular from v2 to v4. Unfortunately I'm unable to find migration guide for v2 to v3. I did found migration guide for v3 to v4.
> 
> Could you please guide me on upgrading from v2 to v3 then finally to v4 ??

Did you find a solution?

**Comment by a-h-abid** [comment]
> > Hi there,
> > My team is planning to upgrade Core-UI Angular from v2 to v4. Unfortunately I'm unable to find migration guide for v2 to v3. I did found migration guide for v3 to v4.
> > Could you please guide me on upgrading from v2 to v3 then finally to v4 ??
> 
> Did you find a solution?

Nope.

For now we are just upgrading to v4 and fixing whatever issues shown.
