### ISSUE TITLE
Carousel touch slide

### ISSUE THREAD

**Issue by juanmmett** [coreui/coreui-angular#144]
For carousel control, using a mobile device's browser, is there a way to scroll through slides by dragging with your finger instead of pressing the next/previous buttons?

**Comment by xidedix** [comment]
Carousel doesn't support swiping on touchscreen devices at the moment.
We're looking into adding this functionality.

**Comment by xidedix** [comment]
@juanmmett thanks! 
fixed in `@coreui/angular` version `4.2.13`
