### ISSUE TITLE
Date picker Bug in Modal

### ISSUE THREAD

**Issue by kernle27** [coreui/coreui-angular#145]
Hej i have an Issue with the Date picker
Any idea?

.![IMG_20221108_210101.jpg](https://user-images.githubusercontent.com/7137215/200663422-d80a5ad1-b378-4bd6-9746-a2895db67292.jpg)

**Comment by xidedix** [comment]
@kernle27 looks like you've got style `overflow: hidden` or sth like this, somewhere inside c-modal 
btw - the latest version is 4.2.13

**Comment by kernle27** [comment]
It was my Fault . Your Tipp Helped me one other component in my nested component had the overflow hidden attribute. Now its working like a charm thanks 👍
