### ISSUE TITLE
Call a shared modal component from another component

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#146]
Please add on how to call a shared modal component from another component. 

Thanks

**Comment by xidedix** [comment]
@32x0lf 
As far as I understand, you'll need a service provided in root to call a shared modal with an Observable. Your another component instance, existing in your app, subscribes to the observable and receives notifications.

**Comment by xidedix** [comment]
@32x0lf you can try to use CoreUI ModalService

```ts
import { ModalService } from '@coreui/angular';

@Component({...})
export class YourComponent {
  constructor(
    private modalService: ModalService
  ) { ... }
...
   this.modalService.toggle({show: true, id: 'sharedModal'})
...
}

```

**Comment by 32x0lf** [comment]
Thanks will try this

**Comment by xidedix** [comment]
@32x0lf updated

**Comment by 32x0lf** [comment]
> @32x0lf you can try to use CoreUI ModalService
> 
> roughly sth like this:
> 
> ```ts
> import { ModalService } from '@coreui/angular';
> ...
> 
> @Component({...})
> export class YourAnyComponent {
>   constructor(
>     private modalService: ModalService
>   ) { ... }
> ...
>    this.modalService.toggle({show: true, id: 'sharedModal'})
> ...
> }
> ```
> 
> ```ts
> import { ModalComponent, ModalService } from '@coreui/angular';
> import { Subscription } from 'rxjs';
> 
> @Component({ ... })
> export class DefaultLayoutComponent implements AfterViewInit {
> 
>   constructor(
>     private modalService: ModalService,
>    ...
>   ) { ... }
> 
>   private modalSubscription!: Subscription;
>   public modalVisible = false;
> 
>   @ViewChild('modal') private modal!: ModalComponent;
> 
>   ngAfterViewInit(): void {
>     this.modalSubscription = this.modalService.modalState$.subscribe(next => {
>       if (next.id === this.modal.id) {
>         this.modalVisible = next.show;
>       }
>     });
>   }
> ```
> 
> ```
> // excerpt default-layout.component.html
> // ...
> <c-modal id="sharedModal" #modal='cModal' [visible]="modalVisible">
>   <c-modal-header>
>     <h5 cModalTitle>App Modal</h5>
>     <button (click)="modalVisible=false" cButtonClose></button>
>   </c-modal-header>
>   <c-modal-body>
>     Text in a shared modal
>   </c-modal-body>
> </c-modal>
> ```

Hi xidedx,

I follow this code but it doesn't work. what did I missed? I put this inside a method```this.modalService.toggle({show: true, id: 'sharedModal'})``` and call it from the button click event.

**Comment by xidedix** [comment]
@32x0lf 
- Where is your `c-modal` html code placed? 
- Can you display your shared modal from there?
- What's the id attribute of your modal?

**Comment by 32x0lf** [comment]
> 
Where is your c-modal html code placed? It is on my sharedModal component.
Can you display your shared modal from there? I cannot make it display, if calling my sharedModal from another component.
What's the id attribute of your modal? sharedModal.

**Comment by 32x0lf** [comment]
> @32x0lf
> 
> * Where is your `c-modal` html code placed? **It is on my sharedModal component.**
> * Can you display your shared modal from there? **I cannot make it display, if calling my sharedModal from another component.**
> * What's the id attribute of your modal? **sharedModal.**

**Comment by xidedix** [comment]
@32x0lf 
Where is your SharedModalComponent then? It has to be placed high in DOM - AppComponent or DefaultLayoutComponent.

**Comment by 32x0lf** [comment]
> @32x0lf Where is your SharedModalComponent then? It has to be placed high in the DOM - AppComponent or DefaultLayoutComponent.

I created a folder called modals and it is placed on that folder. This is not how to do it?

**Comment by xidedix** [comment]
@32x0lf It doesn't matter where you put the code on the file system.  The question is, where does your modal component Html render on the running app?

You have at least two options:
- Place your shared modal component markup and handling at the AppComponent level (the highest) or DefaultLayoutComponent level. 
- Dynamically inject your shared modal component with the createComponent function to create an instance of a ComponentRef and attach it somewhere, say, an ApplicationRef. 

It's your call.

**Comment by 32x0lf** [comment]
can you pls show me in stackblitz? if that's ok with you. My code still don't work I already put the html code inside default layout and the problem is when I call it from the other component it won't work.

**Comment by xidedix** [comment]
@32x0lf all required code you'll find above, I am afraid. 

Here is your working stackblitz [CoreUI Angular Modal Example](https://stackblitz.com/edit/angular-ivy-fzhi5g) for the first option. I believe it might help you to tackle the problem. The other option with `createComponent` shouldn't be much different.

**Comment by xidedix** [comment]
@32x0lf 
Here is the example for the second option - [CoreUI Angular Modal Dynamic](https://stackblitz.com/edit/coreui-angular-modal-a2jrujt). 
It shows the basic concept while being more flexible and probably more convenient for you.

**Comment by 32x0lf** [comment]
Does shared modal doesn't work on free version? I still don't get it to work. I am using a free for testing and decide later if we will buy the pro version.

**Comment by xidedix** [comment]
@32x0lf 
Have you seen the examples on stackblitz? 
Both examples use the free version. Do they work on stackblitz? Yes, they do. They do work on free version. 
It looks like you missed something.

**Comment by 32x0lf** [comment]
> @32x0lf Have you seen the examples on stackblitz? Both examples use the free version. Do they work on stackblitz? Yes, they do. They do work on the free version. It looks like you missed something.

Hmm. I think I missed something.

**Comment by xidedix** [comment]
> Hmm. I think I missed something.

@32x0lf I wonder what...

**Comment by 32x0lf** [comment]
@xidedix  it is now working thank you for sharing the code. I have another question. How can I pass data to modal?
