### ISSUE TITLE
Accordion in Angular adding collapse inside item

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#147]
Adding a collapse inside accordion to show or hide a certain fields / controls and adjust the height. In order to achieve this, I added a button that will trigger the collapse and a css

`:host ::ng-deep .accordion-item:last-of-type {
  .accordion-collapse {
    height: auto !important;
  }
}`
  The collapse works with height set to auto, but when I click the toggle in accordion, all the controls disappear and it will not close. 

- Operating system and version (Windows 11)
- Browser and version (Microsoft Edge)

![image](https://user-images.githubusercontent.com/21064877/201119758-95716be8-005f-48bb-83c6-6ae2e9fbd7ba.png)

**Comment by xidedix** [comment]
@32x0lf any sample code?

**Comment by 32x0lf** [comment]
This is only a sample code with multiple controls 
`<c-col xs="12">
        <c-accordion [alwaysOpen]="false" [flush]="false" class="shadow mb-4">
            <c-accordion-item #item0="cAccordionItem" [visible]="true" >
                <ng-template cTemplateId="accordionHeaderTemplate">
                    <button (click)="item0.toggleItem()" [collapsed]="!item0.visible" cAccordionButton >
                        <strong>Filters</strong>
                    </button>
                </ng-template>
                <ng-template cTemplateId="accordionBodyTemplate">
                    <form [cFormFloating]="true" >
                        <c-row [gutter]="{g: 2}">
                            <c-col class="m-3">
                                <label cLabel for="floatingSelect">InputBox</label>
                                <select cSelect id="floatingSelect" sizing="sm">
                                    <option>All</option>
                                    <option value="1">test</option>
                                    <option value="2">test</option>
                                    <option value="3">test</option>
                                </select>
                            </c-col>
                            <c-col class="m-3">
                                <label cLabel for="floatingSelect">From Date</label>
                                <input type="text"
                                value="11/07/2022"
                                class="form-control"
                                bsDatepicker>
                            </c-col>
                            <c-col class="m-3">
                                <label cLabel for="floatingSelect">To Date</label>
                                <input type="text"
                                value="11/07/2022"
                                class="form-control"
                                bsDatepicker>
                            </c-col>
                        </c-row>
                        <c-row [gutter]="{g: 2}">
                            <c-col class="m-3">
                                <label cLabel for="floatingSelect">InputBox</label>
                                <input cFormControl id="validationCustom03" required type="text" sizing="sm"/>
                            </c-col>
                            <c-col class="m-3">
                                <label cLabel for="floatingSelect">To Date</label>
                                <input type="text"
                                class="form-control"
                                bsDatepicker>
                            </c-col>
                            <c-col class="m-3">
                                <label cLabel for="floatingSelect">Product</label>
                                <select aria-label="Small select example" cSelect sizing="sm">
                                    <option>All</option>
                                    <option value="1">Test - test@test.com</option>
                                    <option value="2">TestUser - test@test.com</option>
                                    <option value="3">User - test@test.com</option>
                                </select>
                            </c-col>
                        </c-row>
                        <c-row [gutter]="{g: 2}" [visible]="visibleFilter" cCollapse>
                            <c-col class="m-3">
                                <label cLabel for="floatingSelect">Portal</label>
                                <select cSelect id="floatingSelect" sizing="sm">
                                    <option>All</option>
                                    <option value="1">regular</option>
                                    <option value="2">not regular</option>
                                </select>
                            </c-col>
                            <c-col class="m-3">
                                <label cLabel for="floatingSelect">Status</label>
                                <select aria-label="Small select example" cSelect sizing="sm">
                                    <option>All</option>
                                    <option value="1">Active</option>
                                    <option value="2">InActive</option>
                            </c-col>
                            <c-col class="m-3">
                                <label cLabel for="floatingSelect">InputBox</label>
                                <input cFormControl id="validationCustom03" required type="text" sizing="sm"/>
                            </c-col>
                        </c-row>
                        
                        <c-row [gutter]="{g: 2}">
                            
                            <c-col class="m-3" align="start">
                                <button (click)="toggleCollapse()" cButton class="me-1" color="primary">{{buttonMessage}}</button>
                            </c-col>
                            
                            <c-col class="m-3" align="end">
                                <button cButton color="warning" shape="rounded-pill" (click)="Get()">
                                    <c-spinner aria-hidden="true" size="sm" *ngIf="isLoadedButton"></c-spinner>
                                    Submit</button>
                            </c-col>
                        </c-row>
                    </form>
                </ng-template>
            </c-accordion-item>
        </c-accordion>
    </c-col>`

**Comment by xidedix** [comment]
@32x0lf I cannot reproduce the issue, it works or, I missed your point. 
![image](https://user-images.githubusercontent.com/20643598/201150156-129496e2-ad67-40f1-af5b-36b649589a87.png)

**Comment by xidedix** [comment]
@32x0lf btw, make sure you've got the latest `v4.2.13`

**Comment by 32x0lf** [comment]
> @32x0lf btw, make sure you've got the latest `v4.2.13`

Sorry, I edited the code. Please try it again. There is another button that will toggle hide/show the last row and added the css style.

When you click the toggle from the accordion that's when it goes empty.

**Comment by xidedix** [comment]
@32x0lf Still works...

---
![image](https://user-images.githubusercontent.com/20643598/201161373-60b6aa4c-7988-4027-b5a9-2255fd486511.png)
---
![image](https://user-images.githubusercontent.com/20643598/201161607-4afb454c-8068-496d-8df8-5cba3b28c935.png)
---
![image](https://user-images.githubusercontent.com/20643598/201161702-c48b516a-0e59-4618-9811-bd6b56f72327.png)

**Comment by xidedix** [comment]
@32x0lf Are you sure you've got the latest `4.2.13` version of `@coreui/angular`?

**Comment by 32x0lf** [comment]
> @32x0lf Are you sure you've got the latest `4.2.13` version of `@coreui/angular`?

How can I check the version of coreui?

**Comment by 32x0lf** [comment]
> :host ::ng-deep .accordion-item:last-of-type { .accordion-collapse { height: auto !important; } }

did you add this?

**Comment by xidedix** [comment]
> > @32x0lf Are you sure you've got the latest `4.2.13` version of `@coreui/angular`?
> 
> How can I check the version of coreui?

-  `npm ls @coreui/angular`
or
- see `node_modules/@coreui/angular/package.json`

**Comment by xidedix** [comment]
> > :host ::ng-deep .accordion-item:last-of-type { .accordion-collapse { height: auto !important; } }
> 
> did you add this?

Works with and without this...

**Comment by 32x0lf** [comment]
> 
![image](https://user-images.githubusercontent.com/21064877/201169534-46f23c9e-b460-4d1b-9810-0979b29e8112.png)

**Comment by 32x0lf** [comment]
How can I update coreui?

**Comment by xidedix** [comment]
> How can I update coreui?

from your project root directory run:

`npm install @coreui/angular@latest`

**Comment by xidedix** [comment]
@32x0lf one more question - have you got imported `SharedModule` ?

**Comment by xidedix** [comment]
see also: https://stackblitz.com/edit/angular-ivy-yjkctj

**Comment by xidedix** [comment]
@32x0lf 
see also: https://stackblitz.com/edit/angular-ivy-yjkctj

**Comment by 32x0lf** [comment]
It works now. I updated to the latest version. Thanks a lot for helping.

**Comment by xidedix** [comment]
> > @32x0lf one more question - have you got imported `SharedModule` ?
> 
> I am not sure what you meant, Is that a core ui module?

That's right

```ts
import {
  AccordionModule,
  ButtonModule,
  CollapseModule,
  FormModule,
  GridModule,
  SharedModule,
  SpinnerModule,
} from '@coreui/angular';

@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    BrowserAnimationsModule,
    AccordionModule,
    ButtonModule,
    CollapseModule,
    FormModule,
    GridModule,
    SharedModule,
    SpinnerModule,
    ...
  ],
   ...
})
export class YourModule {}

```

see: https://stackblitz.com/edit/angular-ivy-yjkctj?file=src%2Fapp%2Fapp.component.scss,src%2Fapp%2Fapp.module.ts
working example
