### ISSUE TITLE
Angular v15 support

### ISSUE THREAD

**Issue by gaweCodes** [coreui/coreui-angular#149]
When will core ui angular be ready for Angular v15?

In the next weeks I will do some new projects. It would be nice to do it with Angular 15 and coreui

**Comment by gaweCodes** [comment]
Do you have any update?

**Comment by xidedix** [comment]
@gaweCodes sure! 
CoreUI update to Angular 15 is slated for the very next week.

**Comment by xidedix** [comment]
[`@coreui/angular`](https://www.npmjs.com/package/@coreui/angular/v/4.3.0) for Angular 15 has been released

**Comment by waqqas-meraj-rt** [comment]
Awesome. Do we have a compatibility matrix that clarifies which version of coreui is compatible with which version of angular.

**Comment by xidedix** [comment]
CoreUI | Angular
---|---
4.0 | 13
4.2 | 14
4.3 | 15

**Comment by xidedix** [comment]
see also: https://coreui.io/angular/docs/migration/angular-version

**Comment by meriturva** [comment]
Any way to have UI components marked as standalone?

**Comment by xidedix** [comment]
@meriturva work in progress...
 you can try it out with @coreui/angular `4.4.0-next.0`
