### ISSUE TITLE
Date Picker inside Accordion

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#152]
I have this issue inside the accordion using the date picker pro version.
![image](https://user-images.githubusercontent.com/21064877/203632830-2598d06d-91a7-42e8-a708-309bb088a774.png)

updated to latest version but still not working.

**Comment by xidedix** [comment]
@32x0lf 
cannot reproduce, you can try following:

- make sure your date picker **container** doesn't have style `overflow: hidden;`
- add style `overflow: visible;` to `c-accordion-item`

```html
<c-accordion-item ...  style="overflow: visible;">
  ...
</c-accordion-item>
```

**Comment by 32x0lf** [comment]
Thanks @xidedix it works
