### ISSUE TITLE
Light theme V3 pro version nested sub menu

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#153]
Hi I am getting this issue in Light theme v3 when clicking the nested sub menu it won't display anything. It was ok when using the free version.

![image](https://user-images.githubusercontent.com/21064877/203633563-17571d78-e350-4757-b04a-1852cdec9bcb.png)

Updated to latest version still not working.

**Comment by xidedix** [comment]
fixed in `4.2.17`
