### ISSUE TITLE
Sample code for cell color in smart table

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#154]
Hello,

In the document there is no sample code for cell color in smart table component. I was  trying to give a cell color based on the data.
like for example:  valid or invalid, if it is valid I want to color the whole row with green or any color and red for invalid. Like what's in the document. I want to achieve the same as that.
![image](https://user-images.githubusercontent.com/21064877/204603869-2f27d339-4a2c-4dbc-800c-ce7ef2d308b7.png)

Thank you in advance.

**Comment by xidedix** [comment]
@32x0lf as a temp workaround you can pass `cTableColor` for each `td` in a `tr` in `ng-template cTemplateId="tableData"`
sth like: 

```html
<c-smart-table ...>
  ...
  <ng-template cTemplateId="tableData" let-columnName="columnName" let-item="item" let-tdContent="tdContent">
    <td [cTableColor]="item.status==='Banned' ? 'danger' : 'success'">
      {{tdContent}}
    </td>
  </ng-template>
</c-smart-table>
```

See: https://coreui.io/angular/docs/components/smart-table#basic-usage

**Comment by 32x0lf** [comment]
@xidedix 

Thank you for the solution.
