### ISSUE TITLE
Sidebar Collapse all on click

### ISSUE THREAD

**Issue by kernle27** [coreui/coreui-angular#159]
Hejoo,

A Question is this a Bug or did  i somenthing wrong?
If i Click in Sidebar on an Child he Complete Links are Collapse to "close" State.
How can i avoid that ? 

Hope you can help me.

Thanks

**Comment by kernle27** [comment]
Hej @xidedix,

Thanks for your fast response.
so what i can tell i have this settings like u see the Picture.
And now if i click on an child navitem under a parent all childs collapses to the closed state. 

![image](https://user-images.githubusercontent.com/7137215/207534821-38952d0d-3b54-49f3-ac0e-d8a5ba74c3ba.png)

**Comment by xidedix** [comment]
@kernle27 cannot reproduce...

1. what happens if you try an `url` with a starting slash like: 
- `/admin`
- `/admin/belegauswertung`

```ts
export const navItems: INavData[] = [
  {
    name: 'Auswertungen',
    url: '/admin',
    iconComponent: { name: 'cilMenu' },
    children: [
      {
        name: 'Belegauswertung',
        url: '/admin/belegauswertung'
      },
      ...
```

2. Is `/admin` at the first level of your sidebar-nav menu?
3. What do you see at the address bar of your web browser for `Belegauswertung`? It should be `http://localhost:4200/#/admin/belegauswertung` or `http://localhost:4200/admin/belegauswertung`
4. What's your version of `@coreui/angular`?

**Comment by kernle27** [comment]
@xidedix 
you are great men 😉 it works!!!
But now the sidebar after the login all childs are expanded .

**Comment by xidedix** [comment]
@kernle27 well, they are expanded, because they all match an active route... huh... 🤔

**Comment by kernle27** [comment]
@xidedix  well, make sense ;) in this  case i think i need to rethink my handling.
we have different products...
and the Backend give me the product from the user back.. according to that the (first emty) route will be active...
looks like i need a different solution for handling the different products.
any idea to make it better?

**Comment by xidedix** [comment]
@kernle27 

- if you'd prefer to keep your current routing, you may opt to use `dropdownMode="none"` as a temp workaround - it prevents any automatic open/close actions on sidebar-nav-group

```html
<c-sidebar-nav
  [navItems]="navItems"
  dropdownMode="none">
</c-sidebar-nav>
```

We're considering a kind of patch to cover your use case.

**Comment by kernle27** [comment]
Hej @xidedix ,
I have done it already i have a emty route with different urls after admin. Now it works like a charm... If this is a good solution is questionable.. but so far it works for me. I will give ur tip a chance and see what is working better.  

Btw sorry for my bad english and thanks for your Help i appreciate it
