### ISSUE TITLE
Passing Data to modal.

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#161]
Please add in the documents on how to pass data to modal. Thank you

**Comment by xidedix** [comment]
Again, your question is: how to pass some data to any Angular component? It depends! 
Some of your options:
-  Create a service responsible for communication between components - (passing data to a Modal in this case). 
or 
-  Use NgTemplateOutlet to communicate between parent and dynamic child components, with `ng-template` context parameters to pass some data.

**Comment by 32x0lf** [comment]
> Again, your question is: how to pass some data to any Angular component? It depends! Some of your options:
> 
> * Create a service responsible for communication between components - (passing data to a Modal in this case).
>   or
> * Use NgTemplateOutlet to communicate between parent and dynamic child components, with `ng-template` context parameters to pass some data.

Hi @xidedix, I was able to pass data to modal from another component using the dialog angular cdk and inject it inside the modal. My only problem now I am facing is whenever I open and close the modal, the backdrop will become darker and darker.
Image 1 first close
![image](https://user-images.githubusercontent.com/21064877/208913752-10b8d129-840e-4d86-96ff-ce3045324466.png)
Image 2 2nd close.
![image](https://user-images.githubusercontent.com/21064877/208913966-33251d51-4b73-4f32-a105-0224ee8c9b91.png)
Image 3 3rd close.
![image](https://user-images.githubusercontent.com/21064877/208914053-9bb19a77-0288-4753-b9df-c69a1325da1e.png)
Image 4 4th close.
![image](https://user-images.githubusercontent.com/21064877/208914121-64c3c9cb-e70c-4d12-bd34-42549c4fcc3c.png)

**Comment by xidedix** [comment]
@32x0lf It seems you have to remove the backdrop. Since we don't know anything about your implementation, you'll have to find out is it coreui backdrop or cdk backdrop.

**Comment by 32x0lf** [comment]
@xidedix I think from coreui.

this is the code inside the component 
`

Data!: InfoInterface

constructor(
    public dialog: Dialog) { }

ShowModal(){
    this.dialog.open(InfoComponent, {
      minWidth: '300px',
      data : this.Data,
      closeOnDestroy:true
    });
  }
`

and this is from the modal
` 
export class SharedModalComponent implements OnDestroy{

  public modalSubscription!: Subscription;
  public modalVisible = false;

  constructor( 
    private modalService: ModalService,
    public changeDetectorRef: ChangeDetectorRef,
    @Inject(DIALOG_DATA) public data: InfoInterface) { }

 @Input()
    set show(value) {
      this._show = value;
      this.modalService.toggle({
        show: value,
        id: 'sharedmodal,
      });
    }

 get show() {
      return this._show;
    }
    private _show = false;
  
    @Input()
    set hostView(value) {
      this._host = value;
    }
     
    get hostView() {
    
      return this._host;
    }
    private _host?: ViewContainerRef;
   
  
    ngOnDestroy(): void {
      this.modalSubscription.unsubscribe();
    }
  
  
    @ViewChild('modal') private modal!: ModalComponent;


  ngAfterViewInit(): void {
    this.modalSubscription = this.modalService.modalState$.subscribe((next) => {
      if ((next.id ?? next.modal?.id) === this.modal.id) {
        this.modalVisible = next.show;
      }
    });

    setTimeout(() => {
      this.show = true;
      this.changeDetectorRef.markForCheck();
    }, 100);
  }

  handleClose($event: MouseEvent) {
    this.show = false;
    this.changeDetectorRef.markForCheck();
  }

  handleAnimationDone($event: AnimationEvent) {
    if (
      $event.fromState === 'visible' &&
      $event.toState === 'hidden' &&
      $event.phaseName === 'done'
    ) {
       //this.hostView?.get(0)?.destroy();
      this.hostView?.clear();
    }
  }
}
`

**Comment by 32x0lf** [comment]
and this is the shared modal html

```
<c-modal
  id="sharedmodal"
  #modal="cModal"
  backdrop="static"
  [visible]="modalVisible"
  size="xl"
>
  <c-modal-header>
    <h5 cModalTitle>Modal</h5>
    <button (click)="handleClose($event)" cButtonClose></button>
  </c-modal-header>
  <c-modal-body>{{data}}</c-modal-body>
</c-modal>
```

**Comment by 32x0lf** [comment]
is this something can be fixed?

**Comment by 32x0lf** [comment]
@xidedix I think I found the reason, If I add inside card-body I will encounter that behavior. I already tried using service and not the cdk dialog but still the same. and when I tried to use the empty card-body, I will not encounter that issue.

**Comment by 32x0lf** [comment]
@xidedix never mind I missed this (@showHide.done)="handleAnimationDone($event)" .
