### ISSUE TITLE
Not sure if all old downloads are able to use if they use npm install after removing old node modules

### ISSUE THREAD

**Issue by brijeshpant83** [coreui/coreui-angular#162]
We have an angular 9 x (9.0.7) application which using "@angular/router": "^9.0.0","@coreui/angular": "^2.9.0","@coreui/coreui": "^2.1.16", I tried to install my app with node v 12.x but app started showing me TS error like below, though it was working fine few weeks ago.

node_modules/@coreui/angular/lib/sidebar/app-sidebar.module.d.ts:24:21 - error TS2694: Namespace '"/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

My observation is when I am installing with 12.x ,your package were showing angular peerDependencies 14 inside @coreui/angular which suppose to not work with node 12.x. 

"peerDependencies": {
    "@angular/common": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/router": "^14.0.0"
  }

please suggest how we can run old apps with node 12.x, your quick support will be appreciated.

**Comment by xidedix** [comment]
@brijeshpant83 
- Statement [here](https://angular.io/guide/releases#actively-supported-versions) says: _Angular versions v2 to v12 are no longer under support._
- Also node.js v12 reached end-of-life https://github.com/nodejs/release#release-schedule
- Angular versions v9 to v13 support node 12.2 
- If you have to stay with `node 12.2`, it is highly recommended to update your app to Angular 13 see: https://update.angular.io/
- If you have to stay with Angular 9, lock your `@coreui/angular` dependency on version `2.9.x`
- `@coreui/angular`  : `@angular/*` compatibility chart:

CoreUI v2 | Angular
---|---
2.9.x | Angular 9
2.10.x | Angular 10
2.11.x | Angular 11
2.12.x | Angular 12
2.13.x | Angular 13
2.14.x | Angular 14

**Comment by brijeshpant83** [comment]
@xidedix thanks for your prompt help, for now I can run the app by freezing coureui 2.9.1 with node v12.22.

Thanks again.
