### ISSUE TITLE
Smart Table tableFilterValue

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#163]
I was using the tableFilterValue in SmartTable component like this.
`[tableFilterValue]="myValue"` and initialize the value `myValue:string = ' ' `
I can display the value and passed it in tablefiltervalue input however, I got an error in devtools
![image](https://user-images.githubusercontent.com/21064877/211006244-2bf073e4-0110-43bd-9971-b43b9872a8c2.png)
How can I fix this?

**Comment by xidedix** [comment]
@32x0lf We cannot reproduce your issue. 
Nevertheless, make sure you are on the latest version of coreui-angular-pro.

**Comment by 32x0lf** [comment]
> @32x0lf We cannot reproduce your issue. Nevertheless, make sure you are on the latest version of coreui-angular-pro.

What is the latest version for coreui-angular-pro?

**Comment by 32x0lf** [comment]
@xidedix 
 npm install @coreui/angular-pro@latest                                                                                      
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: coreui-pro-angular-admin-template-theme-light-3@4.2.5
npm ERR! Found: @angular/cdk@14.2.7
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"^14.2.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^15.0.0" from @coreui/angular-pro@4.3.6
npm ERR! node_modules/@coreui/angular-pro
npm ERR!   @coreui/angular-pro@"4.3.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by 32x0lf** [comment]
Now, I am getting blank page after issuing --force
![image](https://user-images.githubusercontent.com/21064877/211027992-d5ce2804-cf2f-404e-8e71-b7654635d2f0.png)

How do I fix this?@xidedix

**Comment by xidedix** [comment]
@32x0lf  It seems you have been on Angular 14 and you've forced the installation of Angular 15 libraries. No worries, follow the steps:
- remove `node-modules` folder completely 
- remove `.angular` folder completely
- remove `package-lock.json` file
- edit `package.json` file to make sure all `@angular/*` dependencies shows version `^14.2` and `@coreui/angular-pro` shows version `~4.2`
- run `npm install` without force flag

**Comment by 32x0lf** [comment]
@xidedix 

I'm getting an error when running the command npm install
```npm install                                                                               
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: coreui-pro-angular-admin-template-theme-light-3@4.2.5
npm ERR! Found: @angular/cdk@14.2.7
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"^14.2.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^15.0.0" from @coreui/angular@4.3.4
npm ERR! node_modules/@coreui/angular
npm ERR!   @coreui/angular@"^4.2.13" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!```

**Comment by xidedix** [comment]
@32x0lf  Could you show us what dependencies you have in `package.json` file? Only `@coreui/*` part.

**Comment by 32x0lf** [comment]
@xidedix 

```  "@coreui/angular": "^4.2.13",
    "@coreui/angular-chartjs": "~4.2.4",
    "@coreui/angular-pro": "^4.2.5",
    "@coreui/chartjs": "^3.0.0",
    "@coreui/coreui-pro": "^4.4.1",
    "@coreui/icons": "^2.1.0",
    "@coreui/icons-angular": "^4.2.4",
    "@coreui/utils": "^1.3.1",```

**Comment by xidedix** [comment]
@32x0lf    
it should be "~4.2.x" not "^4.2.x"


- "@coreui/angular-pro": "~4.2.25"
- "coreui/icons-angular": "~4.2.4"

**Comment by 32x0lf** [comment]
@xidedix 

I still get the error 
```npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: coreui-pro-angular-admin-template-theme-light-3@4.2.5
npm ERR! Found: @angular/cdk@14.2.7
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"^14.2.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^15.0.0" from @coreui/angular@4.3.4
npm ERR! node_modules/@coreui/angular
npm ERR!   @coreui/angular@"^4.2.13" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

**Comment by xidedix** [comment]
@32x0lf  error message says, you have `@coreui/angular@4.3.4` somewhere in dependencies...

**Comment by 32x0lf** [comment]
@xidedix 

I can't find it in package.json
![image](https://user-images.githubusercontent.com/21064877/211044148-79e7a6e8-1622-4c42-9e45-a208925c5225.png)

**Comment by xidedix** [comment]
@32x0lf  
It says you have 
`"@coreui/angular": "^4.2.13"`

**Comment by 32x0lf** [comment]
> @32x0lf It says you have `"@coreui/angular": "^4.2.13"`
> 
> Remove it.

@xidedix 

yes I have it. Should I remove it or changed the version?
![image](https://user-images.githubusercontent.com/21064877/211045163-e1d76723-8bde-46ec-81c5-725636668736.png)

**Comment by 32x0lf** [comment]
@xidedix

I was able to install the dependencies but when I run it I got an error in modalservice. 
`error TS2307: Cannot find module '@coreui/angular' or its corresponding type declarations.`
![image](https://user-images.githubusercontent.com/21064877/211046431-8a856047-7256-472b-902e-f40551a34fb3.png)

**Comment by 32x0lf** [comment]
> @32x0lf It says you have `"@coreui/angular": "^4.2.13"`
> 
> Remove it. Or change `^` to `~`.

@xidedix 

It is working now, thanks, but still I got this error before I updated my version, and you advised me to update to the latest version. How do I update my version?
![image](https://user-images.githubusercontent.com/21064877/211047210-a331119a-f2cb-4747-83d9-1f4db298ad89.png)

**Comment by xidedix** [comment]
@32x0lf  
I believe you're on the latest 4.2.25 for Angular 14. 

About your issue - cannot reproduce. How/where do you initialize `myValue` field?

**Comment by 32x0lf** [comment]
@xidedix Thank you for your help. Your the best . This is solved. I noticed, was passing undefined value for the myValue. again, thank you and have a nice day.
