### ISSUE TITLE
Underline in Components/Nav not displaying correctly

### ISSUE THREAD

**Issue by davalbra** [coreui/coreui-angular#164]
Description:
The underline in the Components/Nav is not displaying correctly. This issue occurs on all browsers and devices that I have tested on.

Steps to Reproduce:

Create a new Angular project using CoreUI
Add a Navigation bar to your project using the Components/Nav component
Observe the underline of the Navigation bar

Expected Result when use <c-nav variant="underline">...</c-nav>
The underline of the Navigation bar should be a thin line of the correct color (as specified in the CSS)

Actual Result:
The underline of the Navigation bar doesn't work

Notes:

-- CoreUI version 
![image](https://user-images.githubusercontent.com/74167198/214401472-20f8b64b-c110-4201-a85f-0edbe2f78fac.png)

-- screenshot of the bug 
![image](https://user-images.githubusercontent.com/74167198/214401732-85a00e3c-503e-445d-b9e4-249356854157.png)

--the code snippet that is causing the issue 
![image](https://user-images.githubusercontent.com/74167198/214402064-3e44647e-82fa-41de-a792-3b7b060d182f.png)

--work with
![image](https://user-images.githubusercontent.com/74167198/214402152-f2cddea2-9061-4471-87fe-5745875ef84f.png)

**Comment by xidedix** [comment]
@davalbra `variant="underline"` works for the pro version only, I am afraid. We should mention it in the docs.

**Comment by davalbra** [comment]
Now I know, I was confused because on the CoreUI-Angular web page the information did not tell me anything about it.

**Comment by xidedix** [comment]
docs updated
