### ISSUE TITLE
Module '"@coreui/angular"' has no exported member 'IColumnFilterValue

### ISSUE THREAD

**Issue by felipetkful16** [coreui/coreui-angular#168]
TO USE THIS AMRTTABLE IN SERVER-SIDE EXAmple in tutorial get this error : Module '"@coreui/angular"' has no exported member 'IColumnFilterValue

**Comment by xidedix** [comment]
@felipetkful16 that's correct, smart-table is a part of pro version. We use aliased import in the docs for consistency. 
If you have any questions about pro components, let us know here: https://coreui.io/support/

**Comment by felipetkful16** [comment]
Eu comprei a versao paga amigo, quero saber o motivo de nao estar funcionando

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: xidedix ***@***.***>
Enviado: Friday, February 17, 2023 10:02:16 PM
Para: coreui/coreui-angular ***@***.***>
Cc: felipetkful16 ***@***.***>; Mention ***@***.***>
Assunto: Re: [coreui/coreui-angular] Module ***@***.***/angular"' has no exported member 'IColumnFilterValue (Issue #168)


@felipetkful16<https://github.com/felipetkful16> that's correct, smart-table is a part of pro version. We use aliased import in the docs for consistency.
If you have any questions about pro components, let us know here: https://coreui.io/support/

**Comment by xidedix** [comment]
@felipetkful16 
the answer it is. Simply change the import to the pro version of library. It should be installed by default with the pro template.
