### ISSUE TITLE
Theme Colour

### ISSUE THREAD

**Issue by Muhammadumair0** [coreui/coreui-angular#17]
i have just purchased the angular 6+ theme for 49$ . i just wanted to know that the default color of the theme is white and i have to change that to dark ? 
what should i do ? because i have just purchased this theme because of the the "dark theme".
![image](https://user-images.githubusercontent.com/24972290/41760408-259646d2-75a8-11e8-9f94-5519e25c66d7.png)

**Comment by xidedix** [comment]
Hi @Muhammadumair0 
Please look at `src/scss/style.scss`

**Comment by krakenday** [comment]
hello, i have the same problem, i purchased the angular admin and i want the dark theme!! i dont have comments on style.scss!! can u help me please!!?

**Comment by krakenday** [comment]
/*!
 * CoreUI Pro - Bootstrap 4 Admin Template
 * @version v1.0.8
 * @link http://coreui.io/pro/
 * Copyright (c) 2018 creativeLabs Łukasz Holeczek
 * @license http://coreui.io/pro/license/
 */

// Override Boostrap variables
@import "bootstrap-variables";

// Import Bootstrap source files
@import "node_modules/bootstrap/scss/bootstrap";

// Override core variables
@import "core-variables";

// Import core styles
@import "core/core";

// Import UI Kits
@import "uikits/uikits";

// Custom styles
@import "custom";

**Comment by mrholek** [comment]
1.0.8 is old version you have to download latest version 2.x

**Comment by krakenday** [comment]
thank you for your response i will download "coreui-pro-angular-admin-template-2.0.0" package!!
