### ISSUE TITLE
Calling a modal inside the modal

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#171]
Hi,

I have this modal and I want to call another modal within this modal. When I tried to call the child modal using 
`this.modalService.toggle( {show:true , id: ''childmodal'})` it will just close the parent modal and the child modal did not display as well.
Am I doing something wrong? I have been calling modal from a parent component and it displays. Only calling a modal from a modal did not work for me. Please advise.  Thank you

**Comment by xidedix** [comment]
@32x0lf 
This is by design. One modal window at a time. 
Nested modals aren’t supported as we believe them to be confusing.

**Comment by 32x0lf** [comment]
Do you have any suggestion what alternative way or to use for this scenario @xidedix ?
