### ISSUE TITLE
Daterangepicker Laggs

### ISSUE THREAD

**Issue by kernle27** [coreui/coreui-angular#176]
Hey i have some problems with the Daterangepicker.

If i type in the enddate as example to 31.12.2099 the whole Site gets very laggy and hang.
Any Solution or fixes for this Issue?

**Comment by xidedix** [comment]
@kernle27 
first of all, try to update to the latest 4.4.x (Angular 15)

**Comment by xidedix** [comment]
@kernle27 potential fix on the way

**Comment by xidedix** [comment]
@kernle27 
check it out with the latest v4.4.6

**Comment by kernle27** [comment]
@xidedix thank you for your help. i will give it a try

**Comment by kernle27** [comment]
Hey i have Updated to the newest Version and it worked. Thanks
