### ISSUE TITLE
Angular v16 support

### ISSUE THREAD

**Issue by meriturva** [coreui/coreui-angular#177]
I guess it is just a dependencies update....really simple.

Thanks.

**Comment by gabrieldrozd** [comment]
Any info when it might be done? 😅

**Comment by xidedix** [comment]
Angular | `@coreui/angular` |  note
---|---|---
16.x | `~4.5.x` |  `latest`
15.x | `~4.4.x` | with standalone components 
15.x | ~~`~4.3.x`~~ | deprecated
14.x | `~4.2.x` | |

**Comment by nkelemen18** [comment]
What is the schedule for the pro 4.5.x ?
