### ISSUE TITLE
Showing record count in smart table

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#180]
Hi,

How to add this recordcount and will change every page ie. Showing 2-10 of 92 and etc...
![image](https://github.com/coreui/coreui-angular/assets/21064877/04f5f553-b2f1-4bfd-a1aa-8efdc6f8812f)

Thanks in advance

**Comment by 32x0lf** [comment]
Hi,

any updates? Thanks

**Comment by 32x0lf** [comment]
Hi?

**Comment by xidedix** [comment]
@32x0lf you can add a custom summary row to the table footer. 
See: https://coreui.io/angular/docs/components/smart-table#summary-row
