### ISSUE TITLE
SidebarModule: Clicking on backdrop does not close sidebar on mobile view

### ISSUE THREAD

**Issue by viperage** [coreui/coreui-angular#182]
When importing SidebarModule into a standalone component, when clicking the backdrop on mobile view, it does not close the sidebar.
It seemIt seems to be triggering its own sidebar service. Which has no observers.
![image](https://github.com/coreui/coreui-angular/assets/9549627/d8442b46-4592-484a-ba3a-37188a292d7f)

**Comment by xidedix** [comment]
@viperage what's your version of:
- angular (15/16) ?
- @coreui/angular ?

**Comment by viperage** [comment]
@xidedix I am currently using Angular 16.

I managed to work around it by having importProviderFrom(SidebarModule) in the app.config.ts. 
And for my standalone component I import the individual components and service.

Pardon me if I'm wrong but I suspect that when I import the SidebarModule into my standalone component it created its own SidebarService instead of using the service created at root thus having the issue where the state are not triggered.
