### ISSUE TITLE
Build Issue - version 15  in Github Action

### ISSUE THREAD

**Issue by kajanthan19** [coreui/coreui-angular#184]
Recently I got failed my code build from GitHub action. But the Application build is perfectly working fine in local env

```
"dependencies": 
    "@angular/animations": "^15.0.4",
    "@angular/cdk": "^15.0.3",
    "@angular/common": "^15.0.4",
    "@angular/compiler": "^15.0.4",
    "@angular/core": "^15.0.4",
    "@angular/forms": "^15.0.4",
    "@angular/language-service": "^15.0.4",
    "@angular/platform-browser": "^15.0.4",
    "@angular/platform-browser-dynamic": "^15.0.4",
    "@angular/router": "^15.0.4",
    "@auth0/angular-jwt": "^5.0.2",
    "@coreui/angular": "^4.0.0",
    "@coreui/angular-chartjs": "^2.0.0",
    "@coreui/chartjs": "^3.0.0",
    "@coreui/coreui": "~4.1.3",
    "@coreui/icons": "^2.1.0",
    "@coreui/icons-angular": "^3.0.0",
    "@coreui/utils": "^1.3.1",
```

- Github Action build issue

<img width="1509" alt="Screenshot 2023-06-09 at 10 43 29" src="https://github.com/coreui/coreui-angular/assets/13692047/252eb932-00e3-4653-9e19-59aa60c530ef">

do I need to upgrade the CoreUI or make it older version

**Comment by xidedix** [comment]
@kajanthan19 

for **Angular 15**:

```json
"@coreui/angular": "~4.4.9",
"@coreui/angular-chartjs": "~4.4.7",
"@coreui/icons-angular": "~4.4.7",
```

Important:
it is `~` (tilde) sign, not `^` (caret) sign.

other updates
```json
"@coreui/coreui": "~4.2.6",
"@coreui/chartjs": "^3.1.1",
"@coreui/icons": "^3.0.1",
"@coreui/utils": "^2.0.1",
```

imports update required for `@coreui/utils v2`
- from `import {getStyle, ...} from '@coreui/utils/src`
- to `import  {getStyle, ...} from '@coreui/utils`

**Comment by kajanthan19** [comment]
@xidedix Thank you for your update. 

Unfortunately, we have removed the coreui from the solution.

**Comment by numrauf** [comment]
Same issue at myside also, do i have to update to coreui 4?  it is working fine if i build the project locally...

**Comment by xidedix** [comment]
@numrauf for CoreUI v2 and Angular 15 you have to install `@coreui/angular@~2.15`
```json
"@coreui/angular": "~2.15.1",
```
Important:
it is `~` (tilde) sign, not `^` (caret) sign.

see also: `@coreui/angular` version concordance chart https://coreui.io/angular/docs/migration/angular-version/#coreui-v2

It appears that you have outdated dependencies:
- "@angular/cdk": "^12.0.5",  
- "@angular/google-maps": "^12.2.13",  
- "@angular/material": "^12.0.5",
