### ISSUE TITLE
Multi Select with fewer data

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#186]
Hi,

I am using multiselect with a single select but this time without using virtual scroller since it has only few data to display.
The reason I used multiselect because we want user to search for "xx" in field. My problems are

1. Even if it has fewer data, It still load slower or shows data more than a minute.
2. I used a shared modal, so when the modal pops up and I closed the modal immediately without waiting for those data to populate,
   I got this error
   
![image](https://github.com/coreui/coreui-angular/assets/21064877/11b6937d-4f2b-41eb-a26e-109ff348cb3f)
3. I don't want to use virtual scroller for this.

This is my code in html
```html
 <c-multi-select selectionType="text" formControlName="deal" >
   <c-multi-select-option *ngFor="let item of deal" [value]="item.ddvalue" >{{item.ddtext}}</c-multi-select-option>
```                                        

```ts
this.filterService.getFilter(this.FilterParam).subscribe({
 next: (res:any) => {
   if(res!=null){
     this.deal = res.deallist;
   } 
 }
})
```

I am using Angular 14 and my version is

- angular-pro  `^4.2.39`
- coreui-pro `^4.4.1`

    
Please advise TIA.

**Comment by xidedix** [comment]
@32x0lf 

ad 1. We need more details to investigate your issue. Please do contact us at https://coreui.io/support/

ad 2.

> An error thrown when an action is invalid because the object has been unsubscribed. 

- What happens at line `380`  in `adddeal.component.ts` ?
- You `subscribe()` to filterService.getFilter(). You should also `unsubscribe()` it on destroy. 
- Other option is to use `async` pipe instead of subscription.

**Comment by 32x0lf** [comment]
@xidedix ,

Unfortunately, my boss forgot where he saved the product key, that is why I cannot file to support.

**Comment by xidedix** [comment]
fixed in:
| CoreUI| Angular
|---|---|
| ~4.5.29 | Angular 16 |
| ~4.7.3 | Angular 17 |
