### ISSUE TITLE
Datepicker inside a modal that is in another modal. Datepicker not showing

### ISSUE THREAD

**Issue by fgutierrezg** [coreui/coreui-angular#188]
![Captura de pantalla 2023-10-17 a la(s) 15 06 59](https://github.com/coreui/coreui-angular/assets/64220111/9a23c3c2-c7ce-419c-bf93-72e10d5cd6d4)

All components of the second modal are displayed correctly, except the datepicker. The problem only occurs when displaying the datepicker in the second modal, in the rest of the view it is displayed without problem. Any ideas?

**Comment by xidedix** [comment]
@fgutierrezg any errors in console?
