### ISSUE TITLE
Add queryParamsHandling option to navItems in sidebar-nav

### ISSUE THREAD

**Issue by danisorto** [coreui/coreui-angular#19]
Hello,

Can you add the _queryParamsHandling_ option to the _navItems_ array in the _sidebar-nav_ container?
I need to keep the querystring parameters throughout navigation and when I click on a item the querystring params are erased. - This is the link of the documentation in angular [link](https://angular.io/api/router/RouterLink).

**Comment by vunb** [comment]
@danisorto I got the same problem! Do you have any solutions?

**Comment by vunb** [comment]
Follow this PR #21  I rewrite the same component and add the `queryParams`. Now it works for me! ❤️

**Comment by xidedix** [comment]
Sth like this should have been introduced a long time ago.
Version [v2.6.x](https://github.com/coreui/coreui-angular/releases/tag/v2.6.0) introduced similar changes.
Closing.
