### ISSUE TITLE
Angular v17 support

### ISSUE THREAD

**Issue by LordMrcS** [coreui/coreui-angular#190]
As it has been launched already, do we have an ETA for supporting this version?

**Comment by xidedix** [comment]
@LordMrcS I hope later next week

**Comment by DavidBoman** [comment]
Need any help? I cloned Angular, icons and chart and ran ng update. Also ran all tests successfully. Are there any other blockers for updating?

**Comment by LordMrcS** [comment]
> Need any help? I cloned Angular, icons and chart and ran ng update. Also ran all tests successfully. Are there any other blockers for updating?

I tested aswell, only noticed a single outdated peerDependency problem. Other than that it looks good.

**Comment by xidedix** [comment]
Angular | `@coreui/angular` |  note
---|---|---
17.x | `~4.7.x` |  `latest`
16.x | `~4.5.x` |  
15.x | `~4.4.x` | with standalone components
