### ISSUE TITLE
toaster doesn't fire visibleChange

### ISSUE THREAD

**Issue by Porkechebure** [coreui/coreui-angular#194]
all is latest version as of today.
Chrome, win 11, coreUI.

<c-toaster (visibleChange)="onToastVisibleChange($event)" *ngFor="let pos of positions | slice : 1" [ngClass]="'p-3'" position="fixed" placement="{{pos}}"></c-toaster>

on close visibleChange does anything

Also toaster sample:
https://coreui.io/demos/angular/4.2/default-v3/#/notifications/toasts

has broken doc link

**Comment by AdrianRomanski** [comment]
@xidedix any plans for opening some tasks?

**Comment by xidedix** [comment]
@AdrianRomanski Can you please share some details?

**Comment by AdrianRomanski** [comment]
@xidedix Sorry my message were cut of dunno why. I was asking if you as coreui-angular are planning to open any tasks for open source community.
