### ISSUE TITLE
Use of different Icons aside from Core UI Icons

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-angular#198]
Hi,

Is there any possibilities that we can use our own Icons? or we can use another Icons aside from Core UI?
and if so, is there documentations on how to integrate it?

Hope to hear from you Core UI team.

Thanks in advance.

**Comment by Jan-Nox** [comment]
As extension to this issue, I'm missing the documentation on how to use FontAwesome icons in the Sidebar component of coreUI later than version 5.

All issues and stackoverflow posts regarding this are linked to older versions of CoreUI.

I tried extending the IconComponent object and overriding several methods like getInnerHTML and others related to DOM generation - But I haven't succeeded yet.
I also tried putting a FontAwesome IconComponent object on the fitting object position in the Menu structure - This also didn't work.

Looking forward to hearing from you
Jan Nox

Maybe there's another way?

**Comment by nook24** [comment]
I have the same question. It looks like that it is impossible to use other icons than the CoreUI icons at the moment.
I did not found a way to overwrite the default template, without copy&past all the navigation related files

https://github.com/coreui/coreui-angular/blob/40f7429aab634d19e97c7072c4b7e2b5f1cbf576/projects/coreui-angular/src/lib/sidebar/sidebar-nav/sidebar-nav-group.component.html#L22-L39

I'm using Coreui 5

**Comment by iappwebdev** [comment]
Same question here, the CoreUI Icons are not enough, I need some other icons from FontAwesome. How can I use them?

**Comment by xidedix** [comment]
You can use FontAwesome CSS classes only at the moment, we're planning to introduce svg support later this year.

for example:
use package manager to install FontAwesome
```sh
npm install --save @fortawesome/fontawesome-free
```
import FontAwesome CSS in your `src/scss/styles.scss` file:
```css
@import "@fortawesome/fontawesome-free/css/all.css";
```
use FontAwesome CSS classes in your `src/app/layout/default-layout/_nav.ts` configuration file

```ts
export const navItems: INavData[] = [
  {
    name: 'Dashboard',
    url: '/dashboard',
    icon: 'fa-sharp fa-solid fa-home',
  },
...
```
See also: https://docs.fontawesome.com/web/setup/get-started

**Comment by norbertnagy** [comment]
> You can use FontAwesome CSS classes only at the moment, we're planning to introduce svg support later this year.


Any updates on this?
