### ISSUE TITLE
Disable a item in navIItems

### ISSUE THREAD

**Issue by Cesaragsilva** [coreui/coreui-angular#20]
How Can i disable a item in array navItems? I want see the item in menu, but this item need stay disable for user

**Comment by Cesaragsilva** [comment]
Ok! Thx man!

**Comment by hader-araujo** [comment]
> url: '#" disabled'

it didn't work

**Comment by xidedix** [comment]
please update 
- `@coreui/coreui` to `2.1.3`
- `@coreui/angular` to `2.1.0`

usage example (_nav.js): 
```js
{
  name: 'Disabled',
  url: '/dashboard',
  icon: 'icon-ban',
  attributes: { disabled: true },
 },
```
and let us know if it works for you

**Comment by Cesaragsilva** [comment]
@xidedix perfect man. Worket for me! THX
