### ISSUE TITLE
issue after updating from angular 14 to 15

### ISSUE THREAD

**Issue by smarsh-tejaskatariya** [coreui/coreui-angular#202]
Bug reports must include:

- Operating system and version - Windows 11
- Browser and version Chrome

issue

After upgrading to angular 15 from angular 14, getting below error.

./src/content/scss/vendor.scss?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
File was processed with these loaders:
 * ./node_modules/resolve-url-loader/index.js
 * ./node_modules/sass-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> @charset "UTF-8";
| /* after changing this file run 'npm run webpack:build' */
| /***************************

tried adding
Tried adding

      "stylePreprocessorOptions": {
              "includePaths": [
                "src", "node_modules"
              ]
            }
 in angular.json

also below are package.json dependencies
"@angular/animations": "^15.2.10",
    "@angular/cdk": "^15.2.9",
    "@angular/common": "^15.2.10",
    "@angular/compiler": "^15.2.10",
    "@angular/core": "^15.2.10",
    "@angular/forms": "^15.2.10",
    "@angular/localize": "^15.2.10",
    "@angular/platform-browser": "^15.2.10",
    "@angular/platform-browser-dynamic": "^15.2.10",
    "@angular/router": "^15.2.10",
    "@coreui/angular": "~4.4.9",
    "@coreui/angular-chartjs": "~4.4.7",
    "@coreui/chartjs": "^3.1.2",
    "@coreui/coreui": "~4.2.6",
    "@coreui/icons": "~3.0.1",
    "@coreui/icons-angular": "~4.4.7",

**Comment by xidedix** [comment]
@smarsh-tejaskatariya this error comes from `sass-loader`

- what about your `devDependencies` ?
- what's the file containing `"@charset "UTF-8";`  - _./src/content/scss/vendor.scss_ ?
- see also: 
  - [stylePreprocessorOptions](https://angular.io/guide/workspace-config#style-preprocessor-options)
  - [Angular Update Guide](https://update.angular.io/?l=3&v=14.0-15.0)
  - [CoreUI Angular Versions](https://coreui.io/angular/docs/migration/angular-version)

**Comment by smarsh-tejaskatariya** [comment]
Dev dependencies

 "devDependencies": {
    "@angular-builders/jest": "^17.0.2",
    "@angular-devkit/build-angular": "^15.2.11",
    "@angular/cli": "^15.2.11",
    "@angular/compiler-cli": "^15.2.10",
    "@babel/core": "^7.24.4",
    "@babel/preset-env": "^7.24.4",
    "@babel/preset-typescript": "^7.24.1",
    "@types/chai": "4.3.14",
    "@types/chai-string": "1.4.5",
    "@types/datatables.net": "~1.10.24",
    "@types/jest": "^29.5.12",
    "@types/jquery": "^3.5.29",
    "@types/node": "^20.12.5",
    "@types/selenium-webdriver": "4.1.22",
    "autoprefixer": "^10.4.19",
    "babel-jest": "^29.7.0",
    "chai": "5.1.0",
    "chai-as-promised": "7.1.1",
    "chai-string": "1.5.0",
    "css-loader": "^7.1.0",
    "husky": "9.0.11",
    "jest": "^29.7.0",
    "jest-canvas-mock": "^2.5.2",
    "jest-junit": "16.0.0",
    "jest-preset-angular": "^14.0.3",
    "jest-sonar-reporter": "2.0.0",
    "lint-staged": "^15.2.2",
    "ngx-infinite-scroll": "^14.0.1",
    "prettier": "3.2.5",
    "protractor": "^7.0.0",
    "redux-thunk": "^2.4.1",
    "rimraf": "5.0.5",
    "stubby": "^5.1.0",
    "ts-node": "^10.9.2",
    "tslint": "^6.1.3",
    "tslint-config-prettier": "1.18.0",
    "typescript": "4.9.5",
    "util": "^0.12.5",
    "xml2js": "^0.6.2"
  },
  
  
  vendor.scss
  @import 'custom';

@import "@coreui/coreui/scss/coreui";
@import "@coreui/chartjs/scss/coreui-chartjs";



@import 'e_variables';
