### ISSUE TITLE
cIcon directive change name binding not refresh icon in angular 17

### ISSUE THREAD

**Issue by ProDInfo** [coreui/coreui-angular#203]
Bug reports must include:
- Operating system and version Windows 11
- Browser and version: Edge 123.0.2420.81

The code work on angular 16 and core UI 4.7 but upgrade to angular 17 no work, only load the first time but update the variable icon no refresh:

```
<button cButton cDropdownToggle class="px-2">
  <svg cIcon [name]="icon"></svg>
</button>`
```

**Comment by xidedix** [comment]
@ProDInfo we can confirm the issue

**Comment by xidedix** [comment]
@ProDInfo thanks for heads-up!

fixed in `@coreui/icons-angular`: 
- `4.7.19`
- `5.0.2`
