### ISSUE TITLE
app-breadcrumb.service.ts has wrong import from "rxjs" so causes overhead in resulted bundle

### ISSUE THREAD

**Issue by nazar-kuzo** [coreui/coreui-angular#22]
app-breadcrumb.service.ts has wrong import from "rxjs" so causes overhead in resulted bundle

File
coreui-angular/projects/coreui/angular/src/lib/breadcrumb/app-breadcrumb.service.ts

Line
import { Observable } from 'rxjs/index';

Expected
import { Observable } from 'rxjs';

**Comment by xidedix** [comment]
thanks @nazar-kuzo 
PR welcome!

**Comment by sparun160782** [comment]
I have corrected and committed the code as excepted and also merged the same issue is also at 
@coreui/angular/fesm5/coreui-angular.js which is also corrected

**Comment by xidedix** [comment]
closed by #56
