### ISSUE TITLE
Angular 7 compatibility

### ISSUE THREAD

**Issue by drdmitry** [coreui/coreui-angular#24]
When using `coreui-angular` with Angular 7, npm shows warning messages during the `npm install`:

> npm WARN @coreui/angular@2.0.0-rc.1 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN @coreui/angular@2.0.0-rc.1 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.

In `package.json` it is:
>     "@angular/common": "7.0.0",
>     "@angular/core": "7.0.0",

**Comment by xidedix** [comment]
fot Angular 7 compatibility please update `@coreui/angular` to `^2.2.1`
