### ISSUE TITLE
Remove sidebar and aside menu toggle buttons.

### ISSUE THREAD

**Issue by korn3l** [coreui/coreui-angular#4]
I am not able to hide the sidebar and aside menu toggle buttons.

I tried `<app-header></app-header>`  and `<app-header sidebarToggler="false" asideMenuToggle="false" mobileAsideMenuToggler="false"></app-header>` , but it doesn't seem to work.

Here is a screenshot:
![screenshot from 2018-04-13 16-22-49](https://user-images.githubusercontent.com/1729922/38737160-0d4b20c2-3f37-11e8-82b5-e7447f2c8bfd.png)

**Comment by jblackburn21** [comment]
Try this:

`<app-header [sidebarToggler]=false [asideMenuToggler]=false></app-header>`

**Comment by korn3l** [comment]
@jblackburn21 Thanks, I got it to work with 
`<app-header [sidebarToggler]="false" [asideMenuToggler]="false"></app-header>`

But there are still some inconsistencies like:
1. When providing no inputs `<app-header></app-header>` , both toggles show, but if I have it full screen on my computer, only the aside toggle works , but if I make the window small both toggles will work. In order to make it work in full screen I have to add e.g. `[sidebarToggler]="'lg'"`
2. `[fixed]="true"` doesn't seem to do anything
3. `[mobileAsideMenuToggler]` does something only if set to `false`. I guess it would be better called `hideMobileAsideToggler`

**Comment by bot101** [comment]
I had this same issue and had to manually hide them with CSS

**Comment by 7carlosz** [comment]
[asideMenuToggler]="false"
  [mobileAsideMenuToggler]="false"

**Comment by rajeshtbabu** [comment]
<app-header [fixed]="true" [sidebarToggler]="false" [asideMenuToggler]="false" [mobileAsideMenuToggler]="false" [mobileSidebarToggler]="false">

this  one working perfect..

**Comment by CarlosGabrielTovar1991** [comment]
How can I archieve this in React template?

**Comment by vasconce7os** [comment]
> 
> 
> Try this:
> 
> `<app-header [sidebarToggler]=false [asideMenuToggler]=false></app-header>`

Thanks, it's works for me

**Comment by SEGUL001** [comment]
> @jblackburn21 Thanks, I got it to work with
> `<app-header [sidebarToggler]="false" [asideMenuToggler]="false"></app-header>`
> 
> But there are still some inconsistencies like:
> 
> 1. When providing no inputs `<app-header></app-header>` , both toggles show, but if I have it full screen on my computer, only the aside toggle works , but if I make the window small both toggles will work. In order to make it work in full screen I have to add e.g. `[sidebarToggler]="'lg'"`
> 2. `[fixed]="true"` doesn't seem to do anything
> 3. `[mobileAsideMenuToggler]` does something only if set to `false`. I guess it would be better called `hideMobileAsideToggler`

saved my day with the mobile thing, thanks

**Comment by ngingihy** [comment]
i want to hide only the one on the left?
