### ISSUE TITLE
Additional css classes to NavBar Brand

### ISSUE THREAD

**Issue by prindacerk** [coreui/coreui-angular#44]
Currently navbarBrandFull and navbarBrandMinimized have some properties exposed such as src, width, height, and alt. But what is missing in that list is additional classes. I wanted to make the brand logo image fluid. I tried to apply `img-fluid` class available in bootstrap to my logo but unfortunately it wasn't working. I investigated further and found out that fixed sizes can be set for the logo but not a class.

It would be great if you can expose the class property as well so we can add to what is currently set.

**Comment by xidedix** [comment]
hi @prindacerk 
- update `@coreui/angular` to `v2.3.0`  - now you can pass any valid html attribute for navbarBrand `img`
- in `default-layout.component.html` add `class` to `navbarBrandFull` and `navbarBrandMinimized` configuration object like: 
```html
<app-header
...
[navbarBrandMinimized]="{src: 'assets/img/brand/logo.svg', alt: 'CoreUI Logo', class: 'img-fluid'}"
...
>
```
let us know if it works

**Comment by prindacerk** [comment]
Sorry for the delay. It works perfectly. Thank you.
