### ISSUE TITLE
Breadcrumbs do not update on route updates

### ISSUE THREAD

**Issue by jblackburn21** [coreui/coreui-angular#5]
The current binding in the breadcrumb component does not update as the routes change

`this.breadcrumbs = this.service.breadcrumbs;`

this should be implemented as an observable in the service

**Comment by vbelot** [comment]
Hi mrholek, it does not seem to work for me.
With Angular 6.0.7 & CoreUI-Angular 2.0.0-RC1, I have to click twice to have the breadcumb updated if the menu have children. Without children, it works fine, update is done when changing route.
