### ISSUE TITLE
app-header: setting [mobileAsideMenuToggler]="false" or [asideMenuToggler]="false" causes main menu toggler not to function in mobile view

### ISSUE THREAD

**Issue by fluffynuts** [coreui/coreui-angular#59]
Our client does not want the hamburger toggle for the aside menu to show -- we show via custom code. To hide the aside menu, my app-header has the markup:

```html
<app-header
  class="animated fadeIn"
  [fixed]="true"
  [navbarBrandFull]="{src: 'assets/logo.jpg', width: 89, alt: 'Logo'}"
  [navbarBrandMinimized]="{src: 'assets/logo.jpg', width: 30, alt: 'Logo'}"
  [sidebarToggler]="'lg'"
  [mobileAsideMenuToggler]="false"
  [asideMenuToggler]="false">
...
</app-header>
```

Setting `[mobileAsideMenuToggler]="false"` or `[asideMenuToggler]="false"` causes the app main menu (an `app-sidebar` component) not to respond to clicks on the hamburger icon _but only in mobile view_ (ie when the window area is smaller. Desktop view works fine. Oddly enough, when the aside menu has been toggled open by my code, then the button responds to clicks -- will open if closed, will close if opened. If I open the sidebar and then hide the aside menu, I can't close the sidebar either.

- Operating system: Windows 10
- Browsers: All (Chrome, Edge, Firefox, Safari)

full code for the app-root.component.html, for full context:
```html
<app-header
  class="animated fadeIn"
  [fixed]="true"
  [navbarBrandFull]="{src: 'assets/logo.jpg', width: 89, alt: 'Logo'}"
  [navbarBrandMinimized]="{src: 'assets/logo.jpg', width: 30, alt: 'Logo'}"
  [sidebarToggler]="'lg'"
  [mobileAsideMenuToggler]="false">
<!--  [asideMenuToggler]="false">-->
  <div class="toast-container" (click)="extendLongevity()">
    <div [class]="toastClass">
      <div class="col-12 alert alert-{{ toastTheme }}"
           (mouseenter)="extendLongevity()"
           (mouseleave)="releaseNotification()">
        {{ toastMessage }}
      </div>
    </div>
  </div>
  <ul class="nav navbar-top-links navbar-right">
    <li>
      <a class="nav-link" role="button">
        <button class="navbar-toggler ng-star-inserted"
                type="button"
                (click)="activateMessagesTab();">
          <i class="icon-speech"></i>
          <span class="badge badge-pill badge-warning">{{ notifications.notifications.length }}</span>
        </button>
      </a>
    </li>
    <li>
      <a class="nav-link" role="button">
        <button class="navbar-toggler ng-star-inserted"
                type="button"
                (click)="activateNotificationsTab()">
          <i class="icon-bell"></i>
          <span class="badge badge-pill badge-danger">{{ messenger.messages.length }}</span>
        </button>
      </a>
    </li>
    <li>
      <a class="nav-link" role="button">
        <button
          class="navbar-toggler ng-star-inserted"
          (click)="logout()">
          <i class="fa fa-sign-out"></i>
        </button>
      </a>
    </li>
  </ul>
</app-header>
<div class="app-body">
  <app-sidebar [fixed]="true" [display]="'lg'">
    <app-sidebar-nav
      [navItems]="navItems"
      [perfectScrollbar]></app-sidebar-nav>
    <app-sidebar-minimizer></app-sidebar-minimizer>
  </app-sidebar>
  <main class="main">
    <!-- Main content here -->
    <div class="container-fluid">
      <div id="ui-view">
        <div>
          <div class="animated fadeIn">
            <router-outlet></router-outlet>
          </div>
        </div>
      </div>
    </div>
  </main>
  <app-aside [fixed]="true" id="right-aside">
    <tabset [justified]="true" #asideTabs class="no-tabs">
      <tab id="messages">
        <app-messages></app-messages>
      </tab>
      <tab id="notifications">
        <app-notifications></app-notifications>
      </tab>
    </tabset>
  </app-aside>
</div>
```

**Comment by xidedix** [comment]
hi @fluffynuts 
I have tried to reproduce your issue with no success. It is hard to tell what's really going on, without your custom code for aside menu toggling. To show/hide aside menu on the mobile view, you have to toggle `aside-menu-show` class on `body` element.  That's all. It should not affect the behavior of the sidebar toggler button at all.

**Comment by BelvedereHenrique** [comment]
Works fine here.
I disabled the aside both on mobile and normal view. Here how mine app-header looks:
`
<app-header
  [navbarBrandRouterLink]="['/home']"
  [fixed]="true"
  [navbarBrandFull]="{
    src: 'assets/img/brand/logo.svg',
    width: 89,
    height: 25,
    alt: 'T-Invest'
  }"
  [navbarBrandMinimized]="{
    src: 'assets/img/brand/sygnet.svg',
    width: 30,
    height: 30,
    alt: ''
  }"
  [sidebarToggler]="'lg'"
  [asideMenuToggler]="false"
  [mobileAsideMenuToggler]="false"
>
`
And sidebar:
`
  <app-aside [fixed]="true" [display]="false" *ngIf="false">
`

**Comment by fluffynuts** [comment]
@BelvedereHenrique it's been a very long time since I worked on this project & it's no longer maintained. Since you can't repro, I'm closing this out.

**Comment by ngingihy** [comment]
@fluffynuts @xidedix @BelvedereHenrique do you know how can i change the hambruger icon color?
