### ISSUE TITLE
Hide a item in navIItems

### ISSUE THREAD

**Issue by pnthree** [coreui/coreui-angular#60]
How Can i hide a item in array navItems?

**Comment by xidedix** [comment]
hi @pnthree 

_nav.ts returns a configuration object to populate sidebar-nav

- static way: in `_nav.ts` add `hidden` attribute to item: 
```js
{
  name: 'Colors',
  url: '/theme/colors',
  icon: 'icon-drop',
  attributes: { hidden: true }
 },
```
- dynamic way: write an agular service to set up nav config object dynamically, and subscribe the result in default-layout.component

see also: 
- https://github.com/coreui/coreui-free-angular-admin-template/issues/126
- https://github.com/coreui/coreui-free-angular-admin-template/issues/123
- https://github.com/coreui/coreui-free-angular-admin-template/issues/143

**Comment by pnthree** [comment]
Thank you for prompt response and assistance , it works

Regards
Prince

**Comment by SekouSallah** [comment]
I created a service called authentication in the services folder located at the root of the project. In this service I created a hasRole method which allows you to see if the user has a role and return true. As you can see: public hasRole(roles: string[]): boolean {
    const storedUserRoles = localStorage.getItem("userRoles");
  
    if (storedUserRoles) {
      const userRoles = JSON.parse(storedUserRoles);
      return roles.some(role => userRoles.includes(role));
    }
  
    return false;
  }. Now I want to display this sidebar element only if the user has the "ADMIN" or "PATIENT" role. {
        name: 'Add patient',
        url: '/base/add-patient',
        iconComponent: { name: 'eyelash-puzzle' },
        attributes: { hidden: (authService: AuthenticationService) => authService.hasRole(['ADMIN']) }
      }, at the hidden level it has no effect because it is displayed whether the user has the ADMIN role or not. Help me please
