### ISSUE TITLE
Angular 8 compatibility

### ISSUE THREAD

**Issue by dennisameling** [coreui/coreui-angular#61]
Please add Angular 8 compatibility (as it's now GA). Happy to provide a PR if necessary!

**Comment by xidedix** [comment]
Hi, @dennisameling 
We are at the internal testing stage, and tracking the issues on angular / angular-cli repos in the meanwhile.
PR welcome!

**Comment by dennisameling** [comment]
FYI: just tested with the https://github.com/coreui/coreui-free-angular-admin-template package through `npm link @coreui/angular`, then updating that package to Angular 8.0.0 too and that works well. Is there anything else I can do to help here? :)
