### ISSUE TITLE
How can i disable/hide a single app-sidebar-nav-item?

### ISSUE THREAD

**Issue by Mrutyunjay1992** [coreui/coreui-angular#64]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/coreui/coreui-angular/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/coreui/coreui-angular/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here
- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/coreui/coreui-angular/blob/master/README.md#community)

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to CoreUI
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by xidedix** [comment]
Hi @Mrutyunjay1992 
see: 
- https://github.com/coreui/coreui-angular/issues/20#issuecomment-443259330
- https://github.com/coreui/coreui-angular/issues/60#issuecomment-489324161

**Comment by Mrutyunjay1992** [comment]
Hi @xidedix 
I want to hide, not to disable.

**Comment by Mrutyunjay1992** [comment]
Hi @xidedix 

but

attributes: {hidden: false} or attributes: {hidden: true}

both will hide the nav item.

**Comment by xidedix** [comment]
to unhide an item, remove `hidden` attribute

You probably have to write an angular service and set up nav config object dynamically, then subscribe the result in default-layout.component.

**Comment by xidedix** [comment]
@Mrutyunjay1992 
Ok, we need a way to remove html attribs - like `hidden`.
We'll release a patch later today.

**Comment by xidedix** [comment]
@Mrutyunjay1992 
please update dependencies:
```
"@coreui/angular": "^2.5.1",
```

usage:
`attributes: {hidden: null}` 
removes attribute `hidden`

**Comment by Mrutyunjay1992** [comment]
@xidedix 

Thanks
