### ISSUE TITLE
SidebarNavHelper.isActive should check child items for dropdowns

### ISSUE THREAD

**Issue by maxtacco** [coreui/coreui-angular#67]
Hi,

I have a case when urls of child items do not start with the same path as parent's url. In this scenario item selection is not working as expected. So, is it possible to change SidebarNavHelper.isActive to something like this:

```typescript
public isActive(router, item) {
    const url = item.url;
    if (this.itemType(item) === 'dropdown') {
      if (url === '' || url === '#') {
        return item.children.some((childItem: any) => this.isActive(router, childItem));
      } else {
        return router.isActive(url, false);
      }
    } else {
      return router.isActive(url, true);
    }
  }
```

**Comment by kafo85** [comment]
Hello, 
I had the same problem, but in my case i don't have url in the parent item.

So i use this code as modification : 

`import { ɵq } from '@coreui/angular';

export class AppSidebarNavHelper extends ɵq {
    constructor() {
        super();
    }

    public isActive(router, item) {
        const url = item.url;
        if (this.itemType(item) === 'dropdown') {
            return item.children.some((childItem: any) => this.isActive(router, childItem));
        } else {
            return router.isActive(url, true);
        }
    }
}`

And int the "app.module.ts": 
`AppSidebarNavHelper,
    {
      provide: ɵq,//SidebarNavHelper
      useClass: AppSidebarNavHelper
    }`

**Comment by xidedix** [comment]
@WolfgangVonL 
it is `ɵq` not `eq`

**Comment by WolfgangVonL** [comment]
OK...
I was taught not to foolishly copy and paste but to rewrite to understand what I was doing ! Haha

Anyway, many thanks @xidedix !

**Comment by xidedix** [comment]
@WolfgangVonL @kafo85  

v2.7.4 adds `SidebarNavHelper` to the public-api surface, you can safely: 
- import
```ts
import { SidebarNavHelper } from '@coreui/angular';
```
- extend
```ts
export class AppSidebarNavHelper extends SidebarNavHelper {
  ...
}
```

**Comment by WolfgangVonL** [comment]
Thanks @xidedix !

Is it also possible to extend directive from ?

When opening a sidebar nav dropdown, I'd like to close the others but I can't do that from SidebarNavHelper.
I've found the directive (NavDropdrownDirective) which deals with the "open" class and I would to extend it to owerwrite the toggle function with:

```
let children = this.el.nativeElement.parentNode.children
for(let i=0; i < children.length; i++){
    children[i].classList.remove('open')
}
this.el.nativeElement.classList.toggle('open')
```

My code is working but I can't overwrite the Directive. I've tried that

```
@Directive({
    selector: '[appNavDropdown]
})
class AppNavDropdownDirective extend ɵy {
    private _el;
    constructor(_el: ElementRef){
        super(_el)
    }
    toggle(){
        ...
    }
}

@NgModule({
    declarations: [
        AppNavDropdownDirective 
    ]
})
```

No erros but nothing happens...

**Comment by kriefsacha** [comment]
Please i have an error "Property 'itemType' does not exist on type 'AppSidebarNavHelper'. What is this.itemType ??

**Comment by kriefsacha** [comment]
@xidedix also after your comment i have an error : 

"Module not found: Error: Can't resolve '@coreui/angular/lib/sidebar/app-sidebar-nav.service' in '....'"

**Comment by xidedix** [comment]
@kriefsacha what's your version of `@coreui/angular`?

**Comment by kriefsacha** [comment]
@xidedix 2.7.4

**Comment by xidedix** [comment]
@WolfgangVonL 
> 
> Is it also possible to extend directive from source code?

I am afraid it's not possible for directives (afaik).

**Comment by WolfgangVonL** [comment]
Thanks @xidedix 
Is there any chance that in a future release this feature would be directly implemented in @coreui/angular ?

**Comment by xidedix** [comment]
@WolfgangVonL 

This feature will be available as an option in the upcoming CoreUI v3 for Angular.

**Comment by kriefsacha** [comment]
Do we know when the v3 will be out ? And how do we update from v2 to v3 ?

**Comment by kafo85** [comment]
Hello,

I recently update my solution to use the latest dependecies, including : 
- angular 13
- coreui/angular 4.0.0-alpha.X

But I can't longer extends from the SidebarNavHelper like before

This is the error message : 

Module not found: Error: Package path ./lib/sidebar/sidebar-nav/sidebar-nav.service is not exported from package C:\Projects\Perso\BWAclotBeach\AclotBeach.Web\ClientApp\node_modules\@coreui\angular (see exports field in C:\Projects\Perso\BWAclotBeach\AclotBeach.Web\ClientApp\node_modules\@coreui\angular\package.json)

OR

Module not found: Error: Package path ./lib/sidebar/sidebar-nav is not exported from package C:\Projects\Perso\BWAclotBeach\AclotBeach.Web\ClientApp\node_modules\@coreui\angular (see exports field in C:\Projects\Perso\BWAclotBeach\AclotBeach.Web\ClientApp\node_modules\@coreui\angular\package.json)

Have you an idea for why ?

Thanks

**Comment by kafo85** [comment]
Since V4, it's working without extend "SidebarNavHelper"

For me, you can close this issue...
