### ISSUE TITLE
Can app-header/app-footer/app-sidebar/app-aside components be customised?

### ISSUE THREAD

**Issue by yasserpatel1** [coreui/coreui-angular#70]
Can the build components such as app-header/app-footer/app-sidebar/app-aside be customised?

For example, in app-header tag we have a property navbarBrandFull which accepts a json format having dimensions and src of the image. Instead of image can we simply have a text? Can this type of customisation is possible?

Is the code for these component available anywhere? 

Also, Can I get a list of options present in all these tags?

Hoping for a quick response. Thanks.

**Comment by xidedix** [comment]
Hi @yasserpatel1 

To set navbar brand text only, use prop `navbarBrandText` like `{icon: '🅲', text: '🅲 CoreUI'}` .

The missing [app-header props description](https://github.com/coreui/coreui-angular/blob/master/projects/coreui/angular/src/lib/header/app-header.md)  has just been added for head-start.

Find components code here: https://github.com/coreui/coreui-angular/tree/master/projects/coreui/angular/src/lib

**Comment by yasserpatel1** [comment]
@xidedix 
Can I directly import these components in the project?

**Comment by xidedix** [comment]
@yasserpatel1 
see: src/app/app.module.ts

**Comment by yasserpatel1** [comment]
@xidedix 
Yes. I saw that.
Actually I was checking if I can make some changes in these common component.
I was thinking of adding https://github.com/coreui/coreui-angular/tree/master/projects - projects folder in my project and add its direct importing from this project folder. So that if I make any changes then it will get reflected in my current project.

So, I was asking is this even possible?

**Comment by xidedix** [comment]
@yasserpatel1 why not? :)
just copy the source code to your app, and make it work

**Comment by ngingihy** [comment]
hey @xidedix what if i want to remove the hamburger button from app-header? what should add
