### ISSUE TITLE
Missing types on some components

### ISSUE THREAD

**Issue by Fredx87** [coreui/coreui-angular#72]
The `AppSidebarNavComponent` accepts an array of navItems that are typed as `any`:

```typescript
@Input() navItems: Array<any>;
```

This is bad for typechecking, IDE support, and documentation: it's difficult to understand what you have to pass to the component. I've found the types of these items in the main project: https://github.com/coreui/coreui-free-angular-admin-template/blob/master/src/app/_nav.ts but I think that these types should be added here.

The same issue is present in other components, for example this is the definition of some inputs in the `AppHeaderComponent`:

```typescript
@Input() navbarBrand: any;
@Input() navbarBrandFull: any;
@Input() navbarBrandMinimized: any;
@Input() navbarBrandText: any = {icon: '🅲', text: '🅲 CoreUI'};
@Input() navbarBrandHref: ''; // deprecated, use navbarBrandRouterLink instead
@Input() navbarBrandRouterLink: any[] | string = '';
```

**Comment by xidedix** [comment]
Hi @Fredx87 
You're right. We are going to improve types in `@coreui/angular` v3.
