### ISSUE TITLE
Sidebar minimized (icons only) does not scroll

### ISSUE THREAD

**Issue by mubbo** [coreui/coreui-angular#81]
Current Behavior:
The side bar when minimized does not scroll in order to show the rest of the menu items that are not in the view port. This issue can be seen in the PRO demo version as well https://coreui.io/angular/demo/#/dashboard. 

Expected Behavior:
when using the mouse scroll wheel over the side bar the menu should to allow viewing the entire collapsed menu.

**Comment by major697** [comment]
any resolve?
