### ISSUE TITLE
Make horizontal menu static

### ISSUE THREAD

**Issue by markzolotoy** [coreui/coreui-angular#82]
I have successfully remove sidebar and asidebar by doing this:
`[sidebarToggler]="false"
  [mobileSidebarToggler]="false"
  [mobileAsideMenuToggler]="false"
  [asideMenuToggler]="false"`

Now I want to have a horizontal menu static. It's going to be just a few items that will always fit on the screen and at this time I dont need mobile. So, when I resize the Browser I dont need the menu to respond to it. Any idea how to do it? I've got it working but cannot find a way to make the menu left aligned. Any idea?

Thanks

**Comment by xidedix** [comment]
Hi @markzolotoy 
The answer is: "it depends"... 
Do you want to keep `navbar-brand`? 
If not, the simplest way is to replace `<app-header ...>` component with `<div class="app-header navbar">`

**Comment by markzolotoy** [comment]
So, I have this:
`<div class="app-header navbar fixed-top">`
It helped with alignment. But when I scroll the top menu is scrolling too. Naturally, I only want to scroll the application content area. Any idea how to achieve that?

Thanks

**Comment by xidedix** [comment]
@markzolotoy 
- add class `header-fixed` to html `body`

**Comment by markzolotoy** [comment]
Yea, that helps, but the vertical scroll bar still takes the whole page while it should be for the content area only.

**Comment by xidedix** [comment]
This is the current behavior. We'll see what we can do.
