### ISSUE TITLE
 Error: The global function `$localize` is missing. Please add `import '@angular/localize';` to your polyfills.ts file

### ISSUE THREAD

**Issue by felipelc454** [coreui/coreui-angular#86]
**Hello i'm using coreui angular but when i run ng test i get this error:**

0 specs, 0 failures, randomized with seed 29334
Error during loading: Uncaught Error: The global function `$localize` is missing. Please add `import '@angular/localize';` to your polyfills.ts file. in http://localhost:9876/_karma_webpack_/vendor.js line 70502.

**I searched in several places and found no solution ...**

**Comment by felipelc454** [comment]
Thank you, my problem is run resolved...

**Comment by xidedix** [comment]
Thanks for the follow-up!

see also: https://next.angular.io/guide/migration-localize#why-is-my-tslint-failing
