### ISSUE TITLE
app aside bar nav item icon not appeared 

### ISSUE THREAD

**Issue by didouqen** [coreui/coreui-angular#88]
name: 'Ticket',
      url: '/base',
      icon: 'icon-puzzle',
      children: [
        {
          name: 'Open',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
        },
        {
          name: 'Close',
          url: '/base/breadcrumbs',
          icon: 'icon-puzzle',
        },
        {
          name: 'In Progrss',
          url: '/base/cards',
          icon: 'icon-puzzle',
        }

**Comment by xidedix** [comment]
Hi @didouqen 
- What's your version of node.js, angular, browser, os?
- Any console messages in the browser?
- Have you got icons properly installed (package.json, angular.json)?
