### ISSUE TITLE
Siderbar - Close automaticly child when another open

### ISSUE THREAD

**Issue by kriefsacha** [coreui/coreui-angular#89]
Hi,

I wanted to know if there is a setting or any tool i can use for my problem. Even on your website if we open many child menu on sidebar it's all the same color. I wanted to do something that when the user open a child menu it close the others.

Exemple of the problem : 

![WhatsApp Image 2019-11-11 at 19 13 08](https://user-images.githubusercontent.com/35034421/68606961-3d782900-04b8-11ea-9c0d-40511344e673.jpeg)

Do you know something like that ? Can you help ?

Thanks.

**Comment by kriefsacha** [comment]
My code is like this : 

![image](https://user-images.githubusercontent.com/35034421/68757004-dec7c200-0613-11ea-8c2d-b4772e387931.png)

Please help !

**Comment by kafo85** [comment]
Try this : 
[https://github.com/coreui/coreui-angular/issues/67#issuecomment-565438464](url)

**Comment by kriefsacha** [comment]
Doesn't work. Any news ?

**Comment by xidedix** [comment]
If you need a visual clue for opened dropdowns in the sidebar, you can add some styling in `src/scss/_custom.scss` sth like: 
```scss
// Here you can add other styles
.sidebar .nav-item.nav-dropdown.open {
  .nav-link.nav-dropdown-toggle {
     background-color: $gray-800;
  }
}
```

The previously opened dropdown section closes after clicking on a new item only, as long as there was a selected item in the opened section. 
We once tried automatic dropdown close, and abandoned the idea - it was causing too many animations on sidebar-nav, visually unacceptable.

This feature will be available as an option in the upcoming CoreUI v3 anyway.

**Comment by kriefsacha** [comment]
Do we know when the v3 will be out ? And how do we update from v2 to v3 ?
