### ISSUE TITLE
Nested sidemenu nav - selected child item styling

### ISSUE THREAD

**Issue by filipjnc** [coreui/coreui-angular#9]
I'm absolutely loving CoreUI and it really saves up time and provides a consistent look.

There's just one thing that visually confuses me as well as other people - the styling of the selected child items in a nested sidemenu nav. It is very hard to distinguish the tree structure in the following setup:

![image](https://user-images.githubusercontent.com/16118391/40269927-334fd73a-5b85-11e8-8e51-ed1bb31ded6d.png)

`List` and `Frozen` are children of `Skills`. When `List ` is selected, the styling looks almost identical to that of the top-level items.

My workaround in the meantime is to replace the variable` $sidebar-nav-link-active-bg` to `rgba(0, 0, 0, 0.2)`, then I achieve something a little more viable:

![image](https://user-images.githubusercontent.com/16118391/40269918-0227d36a-5b85-11e8-9e09-4db7c4e31311.png)

I am looking forward to a more intuitive look out of the box!

**Comment by 32x0lf** [comment]
> I'm absolutely loving CoreUI and it really saves up time and provides a consistent look.
> 
> There's just one thing that visually confuses me as well as other people - the styling of the selected child items in a nested sidemenu nav. It is very hard to distinguish the tree structure in the following setup:
> 
> ![image](https://user-images.githubusercontent.com/16118391/40269927-334fd73a-5b85-11e8-8e51-ed1bb31ded6d.png)
> 
> `List` and `Frozen` are children of `Skills`. When `List ` is selected, the styling looks almost identical to that of the top-level items.
> 
> My workaround in the meantime is to replace the variable` $sidebar-nav-link-active-bg` to `rgba(0, 0, 0, 0.2)`, then I achieve something a little more viable:
> 
> ![image](https://user-images.githubusercontent.com/16118391/40269918-0227d36a-5b85-11e8-9e09-4db7c4e31311.png)
> 
> I am looking forward to a more intuitive look out of the box!

You can set it to a custom css and set margin-left

**Comment by 32x0lf** [comment]
I was able to acheive it like this with nested menu
`html .sidebar-nav .nav-group-items .nav-link {
  margin-left:10px;
}`
