### ISSUE TITLE
sidebar menu issue

### ISSUE THREAD

**Issue by premmd94** [coreui/coreui-angular#93]
only one dropdown should open. when I click any one dropdown another open dropdown should close
in sidebar

![Screenshot](https://user-images.githubusercontent.com/22440288/70819687-d7572c80-1dfc-11ea-8599-1d68533951c7.png)

How to solve this issue

**Comment by xidedix** [comment]
The previously opened dropdown section closes after clicking on a new item only, as long as there was a selected item in the opened section. 
We tried automatic dropdown close once, and abandoned the idea - it was causing too many animations on sidebar-nav, visually unacceptable.

This feature will be available as an option in the upcoming CoreUI v3 anyway.
