### ISSUE TITLE
Cannot pass Query Params in nav

### ISSUE THREAD

**Issue by radovansninsky** [coreui/coreui-angular#96]
When passing Query param into url of NavData interface (_nav.ts) navigation fails with following error:
> core.js:6014 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 's01%3Fel%3Dsu'
> Error: Cannot match any routes. URL Segment: 's01%3Fel%3Dsu'

Problem is that parameter url is URL encoded.

navItems example:
```js
export const navItems: NavData[] = [
  {
    name: 'Intro w query param',
    url: '/dashboard?p=something',
    icon: 'icon-home'
  }
]
```

app.routing.ts:
```js
export const routes: Routes = [
  { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
  { path: 'dashboard', component: MyDashboardComponent },
];
```

Additional info:
- OS: Windows
- Browser: Chrome 79.0.3945.117
- coreui version: "@coreui/angular": "^2.5.2"

Similar Issue in coreui-react project: https://github.com/coreui/coreui-react/issues/90
I also tried to provide url as object as suggested in issue above but doesn't work.

**Comment by xidedix** [comment]
Hi @radovansninsky 
- update `@coreui/angular` to `^2.7.2`
- use `linkProps` described here: https://github.com/coreui/coreui-angular/releases/tag/v2.6.0 
like this:
```ts
export const navItems: INavData[] = [
  {
    name: 'Dashboard',
    url: '/dashboard',
    icon: 'icon-home',
    linkProps: { queryParams: { 'p': 'something' } }
  },
]
```
